### ISSUE TITLE
[BUG] IDDT arrow is jerky

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#1050]
**Describe the bug**
When IDDT is enabled, the automap arrow doesn't move smoothly like when IDDT is off.

**Build that the bug occurred in**
Commit `97fbdafc966b50a88e37dc6e347094f49c99496c`
`stable`

**To Reproduce**
Type IDDT and look at the map.

**Expected behavior**
The arrow show move smoothly like with IDDT off.

**Screenshots, NetDemos, & Crash Dumps**
https://github.com/user-attachments/assets/af58dbb7-08bc-4c84-b03b-2e459cc8854e

**Comment by rakohus** [comment]
Possibly related to interpolation, or lack thereof?

**Comment by electricbrass** [comment]
I suspect it's related to interpolation. Compare this video from an earlier version before interpolation was merged in. There's no stutter on the IDDT arrow.

https://github.com/user-attachments/assets/fb850820-6a5e-404f-87b8-90ffd0a72952
