### ISSUE TITLE
Doomguy's Mugface doesn't turn around if hit online.

### ISSUE THREAD

**Issue by Ch0wW** [odamex/odamex#239]
On Singleplayer, whenever the Doomguy is hit, he will turn his face left or right, depending on the angle of the attacker.

However on multiplayer, it will always face straight, and never turn his face around.

It looks like that on the client, the attacker is never declared, triggering this bug.

However, it looks like it will require a protocol change to fix this.

**Comment by leximayfield** [comment]
This requires a protocol change and was fixed in the `protobuf`  branch, so will be released with that version.

**Comment by Ch0wW** [comment]
I have added this feature on the Protobuf branch. I'll reopen it if not totally fixed.
