### ISSUE TITLE
sv_waddownload cvar not working

### ISSUE THREAD

**Issue by DartPower** [odamex/odamex#253]
sv_waddownload cvar not working
Friend can't download wads from server with this is "1"

**Comment by Ch0wW** [comment]
`sv_waddownload` is depreciated as it caused more issues than fixing them. We didn't remove it but it is acting as a dummy CVAR and is expected to be deleted with the 0.9.1 release. 

However, you can use this CVAR instead:

`set sv_downloadsites "http://your.url/"`

http://your.url/ being the website it's located.

**Comment by leximayfield** [comment]
Yes, unfortunately `odasrv` was never really designed to be a file server, and the old implementation was quite slow, full of bugs, and had the potential to slow down the server, so the functionality was taken out of Odamex 0.9.0.

The intended replacement functionality is to host your WAD file using a webhost, and using `sv_downloadsites` to point out where the WAD files can be downloaded.  If you join our discord, somebody might be willing to help you get your WAD files someplace where the downloader can find them.
