### ISSUE TITLE
Very strange things with loading wads on Linux (odasrv)

### ISSUE THREAD

**Issue by DartPower** [odamex/odamex#257]
Version: 0.9.0 (compiled from sources)
OS: Debian GNU/Linux 10 (buster) x86_64

Situation 1:
Server is fine working. But on other restart now server can't load a wads
```
[03:04:49] Could not resolve resource file "BTSX_E1A_OCF.WAD".
[03:04:49] Could not resolve resource file "BTSX_E1B_OCF.WAD".
[03:04:49] Could not resolve resource file "D4V2_OCF.WAD".
[03:04:49] Could not resolve resource file "BTSX1D4V_OCF.WAD".
[03:04:49] Could not resolve patch file "D4V2.DEH".
```
("OCF"(Odamex Compatible Fix) is temporary sub-naming, because hash checks failed)

Server config from preset.
Start config:
```
../server_data/odasrv -config ../configs/d4v2_btsx1.cfg +logfile ../server_data/logs/d4v2_btsx1.log -port 29100 -file ../pwads/btsx_e1a_ocf.wad ../pwads/btsx_e1b_ocf.wad ../pwads/d4v2_ocf.wad ../pwads/btsx1d4v_ocf.wad ../pwads/d4v2.deh 
```
Also tried this thing: e.g. "-file 1.wad 2.wad 3.wad" and this: "-file 1.wad -file 2.wad -file 3.wad" but nothing
Start config contains in home folder (e.g. /home/someusername/anotherfolder/... © Captain Obvious)

Situation 2:
All is identical, but:
```
[02:41:32] DOOM 2: Hell on Earth
[02:41:32] adding /home/dartpower/Servers/Odamex/server_data/odamex.wad
[02:41:32]  (240 lumps)
[02:41:32] adding /home/dartpower/Servers/Odamex/pwads/vacav15_ocf.wad
[02:41:32]  (907 lumps)
W_GetNumForName: STDISK not found!
(checked in: ODAMEX.WAD, VACAV15_OCF.WAD)
```

What im doing wrong? Or this is a bug? o_O

And another bug also:
Files in lower-cased named. 
Also have bug with downloading wads, if this not lower-cased, this is cant downloaded from sites (Windows client)
e.g. in folder: BBBB.wad, in game (if font dont touch my eyes) BBBB.wad, but can't found
And if in folder: bbbb.wad and on file server also this. Downloading is normal.
(Sorry for my bad english XD)

**Comment by Ch0wW** [comment]
Stupid question, but do you set any waddir values?

**Comment by leximayfield** [comment]
What are you using to run your servers?

During development I encountered someone using **supervisord** who encountered strange issues with WAD resolution, but upon trying to set up my own local reproduction on Linux I could not replicate the issue.  I wonder if it's a related problem...

**Comment by DartPower** [comment]
> What are you using to run your servers?

tmux + sh

> Stupid question, but do you set any waddir values?

Using -waddir and/or -iwad  is resolved my problem. Thanks a lot!
But strange, without waddir, iwad file already have in odasrv dir and -file loads files not always.
