### ISSUE TITLE
Allow linking to system JsonCpp and MiniUPnPc libraries

### ISSUE THREAD

**Issue by ghost** [odamex/odamex#261]
Currently the internal jsoncpp and miniupnpc libraries are unconditionally built and statically linked. Respective `USE_INTERNAL_JSONCPP` and `USE_INTERNAL_MINIUPNPC` CMake build options should be implemented to enable users to link against their system-provided libraries.

**Comment by leximayfield** [comment]
I know our version of miniupnpc could probably use some updating, but JsonCpp's modern versions require C++11 and I don't know what that means for API compatibility with our older version that uses C++98.  Are you aware of any compatibility issues with either of these libraries?

**Comment by ghost** [comment]
Gentoo has been linking odamex with the latest version of miniupnpc for some time now with no apparent issues so it can probably be updated with no expected issues. We did encounter trouble when attempting to link with a jsoncpp 1.9.3, so there does appear to be some API difference there; however, jsoncpp 00.11.0 (released last year) was able to link successfully so we can at least update to that for the various bug fixes without worrying about api issues of migrating to the jsoncpp-1.x.x series just yet.

**Comment by chewi** [comment]
I've dealt with miniupnpc and have just had a go at JsonCpp. Surprisingly, I was able to build Odamex against JsonCpp 1.9.5 by just changing `CXX_STANDARD` to `11` instead of `98`. Only the server requires this change, but it works for the client too. So the question is whether you mind bumping the C++ standard at this point. Bear in mind that even the ageing CentOS 7 supports C++11. Otherwise I could make it conditional on `USE_INTERNAL_JSONCPP`, but you may not notice if it breaks later.

**Comment by leximayfield** [comment]
> So the question is whether you mind bumping the C++ standard at this point.

Odamex is currently C++98 for compatibility with retrocomputing targets, most notably the OG Xbox port which has historically been compiled using Visual C++ 2003 and the Microsoft XDK.  There might be a day where we update to C++11, but that day is not going to be anytime soon.

That said, incompatibility with distro libraries has caused issues for us before.  On shorter timescales, we are currently investigating Flatpak as a way of distributing Linux binaries.  At that point, how the distro libraries are configured would be academic for folks who just want to play Odamex on Linux.
