### ISSUE TITLE
Replace include guards with #pragma once

### ISSUE THREAD

**Issue by leximayfield** [odamex/odamex#266]
Include guards are annoying to write and I cannot think of a C++ compiler we support that does not support the feature.

Here's the portability matrix:

https://en.wikipedia.org/wiki/Pragma_once#Portability

The most interesting compiler is GCC, which didn't support them "officially" until 3.4, though checking Bugzilla implies they supported it unofficially and intended to deprecate it much earlier.

**Comment by rakohus** [comment]
Was committed in #603
