### ISSUE TITLE
Implement CVAR Overrides

### ISSUE THREAD

**Issue by fuzztooth** [odamex/odamex#267]
*(Bug 112)*
                    
Cvar Overrides allow you to override certain cvars for certain maps, preventing
you from having to make one config criteria for your server.

I already wrote an implementation for ZDaemon, but would need to rewrite most of
it to make it snap into Odamex

For example... ( ZDaemon example, works with 1.07 and up )

add_cvaroverride map07 sv_infiniteammo true
add_cvaroverride map11 sv_respawnitems true

Whenever the server lands on map07, it'll temporarily override the
sv_infiniteammo cvar to true, and reset it to the server default when the map is
left.

add_cvaroverride map11 hostname ""Classic Map11 Deathmatch""

It allows for a lot of flexibity with minimal intrusion and thus should be
implemented for Odamex 1.0. Since I wrote the original implementation I will
take charge in writing this one.

**Comment by rakohus** [comment]
Pretty sure this was brought in by someone that was not fuzztooth from the old tracker. Whoever it was that volunteered to do this over a decade ago didn't deliver. We would also have issues with making this work with our map system which allows for way more. Someone can reopen a new feature request one day if they want this.
