### ISSUE TITLE
Consistency of weapon firing feedback (visible / audible)

### ISSUE THREAD

**Issue by fuzztooth** [odamex/odamex#270]
*Bug **167**
Posted By: **typone (Tom J.)**
Posted On: **Sun, 19 Mar 2006 16:01:57 GMT**
Last updated **Sun, 30 Mar 2014 21:19:13 GMT***

When the PG / RL is fired, the plasma balls /rockets are displayed and audible _after_ the ping returns, i.e. delayed. Which i think is the way it should work.

With any hitscan weapon (Pistol, CG, SG, SSG) the feedback is different. When any hitscan weapon is fired the sound is audible instantly without delay, whereas the visible feedback (the bullets hit something) is delayed by the ping. With the BFG the charging-up sound starts instantly after pulling the trigger but the plasma ball seems to be delayed as well.

I'd recommend making all of these weapon feedback events consistent (for instance every audible / visible feedback could be played delayed).

**Comment by rakohus** [comment]
Unlagged kind of fixed this and this bug is ancient. Marking wontfix, even though it _kinda_ is fixed
