### ISSUE TITLE
[BUG] Doom2/Plutonia/TNT Map08 Global Sound

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#274]
**Describe the bug**
Currently, when vanilla sound is enabled (co_zdoomsound = 0), sounds are played globally at full volume like they are in EXM8 of UDoom. Over the past week, I've joined in games and players really seem to hate this happening.

**Build that the bug occurred in**
0.9 Stable

**To Reproduce**
Make sure "co_zdoomsound = 0", go to Doom 2 Map08, listen to any sound.

**Expected behavior**
Make exception only apply to EXM8? There is some argument as to whether or not this is one of the intentional "tricks" of the map.

**Screenshots, NetDemos, & Crash Dumps**
N/A

**Additional context**
N/A

**Comment by Ch0wW** [comment]
I have to admit that replicating that bug is not an enjoyable feature (despite our desires to keep the port *as close* as the original) and I'm totally fine to remove it.

**Comment by rakohus** [comment]
This has been solved with PR #382
