### ISSUE TITLE
[FEATURE] Advanced Help Screen (F1 - HELP lump)

### ISSUE THREAD

**Issue by DX-Chain** [odamex/odamex#275]
Currently on Odamex 0.9, the HELP lump (f1 help screen in-game) scales the image to a 4:3 aspect ratio screen like the original doom2.exe

My feature request would be to open up the possibility of using 16:9 (or other aspect ratios) in the HELP lump/screen to allow players that play on 16:9 without any scaling/stretching/collapsing. Additionally, allowing transparency in these lumps/images would open up even greater possibilities for design and presentation of all types of WADs :-)

Here is a video to compare all of the multiplayer Doom ports' handling of the HELP lump/image. Something like ZDaemon's implementation is what my feature request aims to replicate (with a solid transparent color in place of any teal/see-through colors in the image itself):

https://streamable.com/z9c3e4

PS: The HELP lump image on this WAD has a native resolution of 1920x1080. All 3 ports had the resolution set at 1920x1080.

**Comment by bcahue** [comment]
Fixed with #983
