### ISSUE TITLE
[BUG] Cannot scroll through spynext using mwheel after survival mode death

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#280]
**Describe the bug**
In survival mode (g_lives > 0), you will automatically go into spectator mode once you run out of lives. After this happens, you can only move through spynext with F12.

**Build that the bug occurred in**
Odamex 0.9

**To Reproduce**
See bug description.

**Expected behavior**
Mwheel should scroll through available views as it does as a normal spectator.

**Comment by Ch0wW** [comment]
Latest commit in stable may fix the issue, could you confirm it?

**Comment by rakohus** [comment]
Tried it out with 3 local clients. Mwheel did not work for changing spynext POV once booted into survivor-spectator mode.

**Comment by rakohus** [comment]
> Tried it out with 3 local clients. Mwheel did not work for changing spynext POV once booted into survivor-spectator mode.

Disregard. User error. Can confirm it's fixed! Thanks @Ch0wW
