### ISSUE TITLE
[BUG] Can't open certain wads that contains mapinfo lump

### ISSUE THREAD

**Issue by fraansg** [odamex/odamex#282]
In certain wads that contains a mapinfo lump, this cannot be loaded in the port, e.g. **duelpack.wad** load even in vanilla or chocolate-doom, but in Odamex when is loaded the engine crashes, the problem dissapear when the mapinfo lump is **deleted** of the wad file.

The bug occurs in the latest build of the engine (0.9.0) running in MacOS Big Sur.

**Comment by rakohus** [comment]
Duplicate of #279. MAPINFO parsing issue.
