### ISSUE TITLE
LAN server detection (multicast/broadcast)

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#285]
*Bug **194**
Posted By: **denis (Denis Lukianov)**
Posted On: **Fri, 14 Apr 2006 00:12:57 GMT**
Last updated **Thu, 12 Apr 2012 16:31:11 GMT***

would be nice

**Comment by rakohus** [comment]
Going to nuke this issue. It was migrated from the old tracker and we're currently looking at new launchers. This will likely be part of that. Client/Server were the old designation for this bug but it doesn't really apply with our current setup.
