### ISSUE TITLE
[FEATURE] Redundancy and linkage with multiple  master servers

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#287]
*Bug **254**
Posted By: **denis (Denis Lukianov)**
Posted On: **Mon, 13 Nov 2006 10:13:14 GMT**
Last updated **Thu, 20 Mar 2014 05:23:59 GMT***

because i'm not lazy, i get to post this on the bug tracker

this is not an easy problem

**Comment by rakohus** [comment]
We haven't talked about this in 10+ years. Going to close it out. Can file a new issue if/when we finally tackle our masters.
