### ISSUE TITLE
[BUG] Weapons shoot wrong ammo upon switching in certain cases

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#288]
*Bug **269**
Posted By: **ryan (Ryan Nematollahi)**
Posted On: **Fri, 19 Jan 2007 03:51:51 GMT**
Last updated **Sun, 30 Mar 2014 21:20:15 GMT***

Sometimes when the player runs out of ammo and autoswitches weapons, the weapon he switches to will fire the rounds of the previous ammo (ex. player runs out of rocket launcher ammo, autoswitches to super shotgun, supershotgun shoots rockets). Its quite difficult to reproduce.

**Comment by rakohus** [comment]
I actually don't think this is possible anymore with the way weapons work. Now, the weapon will typically switch immediately upon firing to the server weapon. There are still weapon bugs, but not as described.
