### ISSUE TITLE
Ghost Monsters in Coop

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#290]
*Bug **293**
Posted By: **griffiniic (Dr. Zin)**
Posted On: **Sun, 21 Jan 2007 18:56:25 GMT**
Last updated **Sun, 27 Jan 2019 06:34:48 GMT***

There seem to be sporadic instances of ghost monsters in coop, except they occur in maps that do not contain archviles. Suspect monsters are spawned as ghosts.

**Comment by rakohus** [comment]
Replacing with Duplicate #431.
