### ISSUE TITLE
Dehacked music replacement doesn't work

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#292]
*Bug **529**
Posted By: **doomgod (doomgod)**
Posted On: **Sun, 04 Jan 2009 04:02:31 GMT**
Last updated **Thu, 20 Mar 2014 05:21:21 GMT***

A good example is Plutonia 2. It plays music from IWAD.

**Comment by rakohus** [comment]
Testing in Odamex 10 dev build. PL2 music seems to work fine.
