### ISSUE TITLE
Servers aren't checking client wads

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#294]
*Bug **475**
Posted By: **Ralphis (Ralph Vickers)**
Posted On: **Sun, 01 Jun 2008 10:47:34 GMT**
Last updated **Fri, 13 Apr 2012 13:28:52 GMT***

Servers should make sure that clients are using the exact same wad files as the server. As of revision 870, this is not the case.

I began modifying my odamex.wad to test out new flag sprites. I soon found out that even with a modified odamex.wad I could connect to any server. 

Correct behavior is for server to check client's wad and make sure it matches exactly. If the wad doesn't match, player is booted from the server.

**Comment by rakohus** [comment]
pwads now checked and downloaded with new wad downloading system.
