### ISSUE TITLE
HTTP Downloading

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#295]
*Bug **649**
Posted By: **alexmax2742 (Alexander Mayfield)**
Posted On: **Tue, 21 Sep 2010 06:48:45 GMT**
Last updated **Tue, 21 Sep 2010 06:48:45 GMT***

Right now, wad downloading is rather slow.  I think it would be a lot nicer if Odamex could download WAD's from any HTTP source.

New variable:
sv_httpwaddownload

If true, the client will attempt to open a normal HTTP connection to the URL listed in sv_website + the wad name in question.  If found, it will download the file over HTTP.  If not, it will then continue on with attempting to download via sv_waddownload like normal.  Note that it will not try to reimplement wadseeker by searching for the wad anywhere, merely try the URL in sv_website and if it's not there give up.

Bonus feature:
Attempt to also find any file with .zip or other archive and extract the wad from the archive.

**Comment by rakohus** [comment]
10 years after this bug report, Alex killed this. Odamex client now supports this and it's better than this proposed implementation.
