### ISSUE TITLE
Voodoo doll glitch

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#296]
*Bug **327**
Posted By: **gmakermaniac (Albert Brown)**
Posted On: **Sun, 01 Apr 2007 00:44:12 GMT**
Last updated **Thu, 20 Mar 2014 05:21:20 GMT***

The voodoo doll bug is a bug from vanilla doom where dummy players would be spawned which can be used to cause damage to the player it represents.  Though the benefits of this glitch are low, there is one very amazing thing it can be used for: it can (and has been) used to implement logic circuits by having a doll placed on a conveyor which crosses over lines.  Also it has been used for the ""instant suicide effect"" featured in tnt.was map30.

Voodoo dolls dont seem to work at all in the current svn release of odamex.  The player spawning code for cooperative should try to mimick the code of vanilla, including trying to spawn player instances at every spawn point in coop.  Some additional system may need to be implemented to make maps like tnt.wad map30 work completely (die every time you cross the line and telefrag yourself, not only once)

This may not be too hard to fix, I'll consider doing it myself.

**Comment by rakohus** [comment]
Avatar system introduced in Odamex 0.9 by AlexMax. Handles most online coop issues. Any issues going forward regarding this will be specific issues.
