### ISSUE TITLE
[FEATURE] Allow binding to a certain IP Address

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#297]
*Bug **587**
Posted By: **ghostlydeath (GhostlyDeath)**
Posted On: **Tue, 18 May 2010 04:06:35 GMT**
Last updated **Sat, 15 Dec 2012 04:57:41 GMT***

On some servers, you have multiple IP Addresses, and in that case the socket library may decide what it really wants to use.

Would basically be this in i_net.cpp in the function BindToLocalPort

***********************************************************

netadr_t na;

if -bind command line parameter exists
{
    NET_StringToAdr(""<-bind address>"", &na);
    NetadrToSockadr(&na, &address);
}
else  // Any address
    address.sin_addr.s_addr = INADDR_ANY;

***********************************************************

**Comment by rakohus** [comment]
Nobody has clamored for this in the 12 years since the initial tracker entry. Closing.
