### ISSUE TITLE
[FEATURE] Help from command line

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#298]
*Bug **309**
Posted By: **lemonzest (Lemonzest)**
Posted On: **Fri, 26 Jan 2007 17:01:03 GMT**
Last updated **Thu, 20 Mar 2014 05:23:59 GMT***

would be nice if you could get help for odemex/odasrv from the cline with for example /? or -help printing a list of available command line options/arguments.

**Comment by rakohus** [comment]
We're working on making better documentation available via other venues. There is a huge amount of ccmds and cvars that would probably be overkill for that list. Some commands exist to help users already: `cmdlist` `cvarlist` `cvardoc`
