### ISSUE TITLE
Random monster desyncs in online coop

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#299]
*Bug **597**
Posted By: **spleen.the.bloody (Spleen)**
Posted On: **Sat, 24 Jul 2010 04:16:15 GMT**
Last updated **Fri, 14 Oct 2016 21:24:25 GMT***

Monsters seem to randomly desync in coop online, even when testing on a LAN and with sufficient rate/sv_maxrate variables set.  For example, cyberdemons will sometimes show their firing sprites while moving around (a state desync, in this case).

**Comment by rakohus** [comment]
Replacing with Duplicate #431.
