### ISSUE TITLE
5+ Player Coop Spawn Protection

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#300]
*Bug **629**
Posted By: **Ralphis (Ralph Vickers)**
Posted On: **Sat, 04 Sep 2010 23:41:57 GMT**
Last updated **Tue, 15 Nov 2016 06:14:31 GMT***

Most coop maps are only designed for 4 players (since vanilla Doom only have 4 player starts). Of course, Odamex supports much more than 4 players. A problem arises when 5 or more players enter the next level because some players will be telefragged and lose all of their stuff.

Skulltag solves this by just allowing players to keep telefragging each other but having them keep their weapons until they move off the spawn spots. I personally find this method very sloppy and think that Odamex can do it better. Perhaps something like our current sv_unblockplayers except it would only take effect on players when they spawn (and they'd become solid again once they've cleared each other)?

**Comment by rakohus** [comment]
Most coop servers use `sv_unblockplayers` now. I don't think this is an issue worth dealing with for now. Closing.
