### ISSUE TITLE
Multicharset support for hotkeys

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#301]
*Bug **299**
Posted By: **klaasedone (user'ok)**
Posted On: **Mon, 22 Jan 2007 15:41:41 GMT**
Last updated **Thu, 20 Mar 2014 05:24:00 GMT***

would be good. when i go to quit menu or use a bind i must always switch from russian to english to make odamex understand my hotkey, that's not really handy.

**Comment by rakohus** [comment]
Keyboard language support changed going into SDL2 on 0.8. This bug is old. Someone can refile if this is still an issue.
