### ISSUE TITLE
[BUG] AG-Odalaunch on Xbox: Focused widget fails to activate

### ISSUE THREAD

**Issue by odamex-system** [odamex/odamex#307]
*Bug **664**
Posted By: **mwoodj (Mike Wood)**
Posted On: **Sun, 03 Oct 2010 04:20:04 GMT**
Last updated **Sun, 03 Oct 2010 04:49:55 GMT***

This is caused by the fact that the main window does not register as having focus when the application starts even though cycling the focused widget cycles widgets on the main window as if it were the focused window. Making a cursor selection (pressing A) anywhere in the window registers the window focus. Explicitly calling the focus function in the main window constructor with the main window as the function parameter does not seem to resolve the issue. This issue does not affect interaction with the interface using the cursor at all.

**Comment by rakohus** [comment]
Per Hyper_Eye this evening, this is unlikely to be resolved. Closing out.
