### ISSUE TITLE
[FEATURE] Reimplement Weapon Drop on death + more

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#314]
**Describe the solution you'd like to see**
ZDoom used to have sv_weapondrop. We removed it in the early days of the project, but it would be nice to have again as an option.  Behavior should be just to drop the current weapon with the current ammo. 

After talking with a few people, also recommendation for a second form (sv_weapondrop 2) which would drop the player's entire weapon inventory into a backpack (or some other odamex custom sprite to denote a l00t bag).

**Comment by leximayfield** [comment]
Doom's pickups are usually stateless and do the same thing every time given some specific consistent preconditions.  The feature as you describe would require keeping a serialized form of what the player was holding on death.

It wouldn't be a trivial add, but also not the worst thing in the world.  My initial idea would be to add a generic "data" field to each mobj that would start out blank but where we could write some arbitrary type-specific data into each mobj.  In this case it would be the contents of the backpack drop.

**Comment by rakohus** [comment]
Normal weapondrop was reimplemented by @SapientLion in PR #330 and merged into stable

**Comment by rakohus** [comment]
Found a bug. BFG drops as a BFG ball, not the weapon pickup. Will submit a PR shortly.

**Comment by rakohus** [comment]
First part of request was complete, second was not but will reopen with a new feature request at a later time. Thanks to @SapientLion for the patch!
