### ISSUE TITLE
[BUG] Sunlust MAP30 Freeze

### ISSUE THREAD

**Issue by decino** [odamex/odamex#318]
**Describe the bug**
Odamex locks up when trying to play MAP30 of Sunlust. Entering the map as a spectator works fine, but the moment you spawn as a player everything freezes.

**Build that the bug occurred in**
v0.9.0

**To Reproduce**
Load up MAP30 -- either through the client or server. If client, the game will freeze the moment you switch to the map. If server, the game will freeze the moment the player starts playing as a non-spectator.

**Expected behavior**
It shouldn't freeze.

**Screenshots, NetDemos, & Crash Dumps**
N/A.

**Additional context**
N/A.

**Comment by leximayfield** [comment]
Thanks for the bug report - I knew about this issue happening as far back as 0.8.x but was unable to get to the bottom of it in time for 0.9.0.
