### ISSUE TITLE
[FEATURE] More console shortcuts

### ISSUE THREAD

**Issue by Ch0wW** [odamex/odamex#321]
**Is your feature request related to a problem? Please describe.**
Odamex's console is quite good the way it is right now ; however, compared to other Quake-Engine games or ports, I noticed we miss some useful shortcuts.  

**Describe the solution you'd like to see**
Add a few more console shortcuts, such as the following:
- ALT/CTRL + BackSpace = delete the last word
- ALT + DEL = delete the word before the cursor

**Comment by rakohus** [comment]
Could be good to have.

**Comment by bcahue** [comment]
This was resolved with #804 but I forgot to close this ticket.
