### ISSUE TITLE
[FEATURE] Add a CVAR to uncollide with other players' projectiles

### ISSUE THREAD

**Issue by Ch0wW** [odamex/odamex#323]
**Is your feature request related to a problem? Please describe.**
In Cooperation, people often collide with Rockets, and can be problematic for some new players.

**Describe the solution you'd like to see**
An extension to `sv_unblockplayers` that doesn't make player projectiles (mostly rockets) collide with each other.

**Comment by rakohus** [comment]
Added by KBlair via PR in the Odamex 10 dev builds. `sv_unblockplayers` now allows friendly projectiles to pass through teammates.
