### ISSUE TITLE
[BUG] Incorrect sector lighting in multiplayer

### ISSUE THREAD

**Issue by DCGRetrowave** [odamex/odamex#325]
**Describe the bug**
Occasionally in a multiplayer game, some sectors don't display the correct brightness value.  Sometimes, the brightness even changes later on.  This seems to occur primarily with doors.  They either display the same brightness as the nearest bright sector or the same darkness as the nearest dark one.  I've personally encountered this a few times in the upcoming DOOM 87 megawad as I know how bright the sectors should be since I'm the map designer.  I just spotted a similar issue on DOOM II's MAP24 in the glowing blue room with the Pinkies.  The sectors that are supposed to glow weren't glowing at all.  They were only displaying the lowest brightness value that they reach during the glow effect.  These issues don't occur in single player so it appears to be an issue with lighting information being synced between the server and client.

**Build that the bug occurred in**
Odamex 0.9.0 and 0.8.3 (I remember seeing it there too, but not as often).

**To Reproduce**
While the incorrect brightness seems to be inconsistent under the doors I've spotted it on, the glowing sector issue on The Chasm seems to occur every time I connect to a server running the map.  Go to MAP24, head over to the blue room with the Pinkies near the end, and the room will appear very dark without the intended glowing lights.

**Expected behavior**
The lighting should display the same way it does in single player and in other ports.  The lighting effects such as glowing lights should be working too.

**Screenshots, NetDemos, & Crash Dumps**
No glowing lights in multiplayer.  The room is very dark and stays this way.
![Odamex_COOP_20210428_132234](https://user-images.githubusercontent.com/74083687/116463359-3a016a80-a830-11eb-9a07-eb8c986abc3d.png)
The room glows in single player as it does in other ports so it can get brighter while still being dark temporarily.
![Odamex_SOLO_20210428_132736](https://user-images.githubusercontent.com/74083687/116463444-4f769480-a830-11eb-8e22-c29babdf800c.png)

**Comment by bcahue** [comment]
This may have been fixed with #745.

**Comment by rakohus** [comment]
Tested in latest build today and this has been resolved for a while
