### ISSUE TITLE
[FEATURE] Widescreen Asset Support

### ISSUE THREAD

**Issue by OpenRift412** [odamex/odamex#327]
I think having support for widescreen assets would be a pretty cool feature to have, like titlepics, interpics, status bars, etc. This seem doable?

**Comment by leximayfield** [comment]
I'd love to, but I'm actually not decided on what the best idea to support these resources is.  Most other ports don't have to care about multiplayer compatibility, and I'd hate for "I want to use widescreen resources' to become "Whoops, I'm using the wrong IWAD, can't join the server" or "Whoops, I reached MAP02 and the game kicked me out".

**Comment by rakohus** [comment]
This is related, in part, to bug #275

**Comment by OpenRift412** [comment]
> I'd love to, but I'm actually not decided on what the best idea to support these resources is. Most other ports don't have to care about multiplayer compatibility, and I'd hate for "I want to use widescreen resources' to become "Whoops, I'm using the wrong IWAD, can't join the server" or "Whoops, I reached MAP02 and the game kicked me out".

I'm not talking about the different IWADs that come with the unity port, I'm talking about standalone PWADs you could autoload (like chocolate and crispy doom) when the game launches, then any graphics would be overridden by the server's PWADs.

**Comment by leximayfield** [comment]
If you're talking about the widescreen assets WADs you made that that I've seen on Doomworld, then it's nearly the same problem to solve.  Your asset WADs are okay, but I don't want people overriding map or ingame graphic data.

I'd want to come up with some sort of whitelisting system to ensure that only the lumps we allow to be overridden are overriden - kind of like a "pure" system from Quake.

**Comment by seanmleonard** [comment]
Adding a [link](https://www.doomworld.com/forum/topic/121385-widescreen-assets-pack-and-appreciation-thread/) to the Doomworld thread to provide an example WAD for the assets.

**Comment by seanmleonard** [comment]
I agree with Lexi re: autoloading of additional client-side WADs would require whitelisting only certain resources that would not affect gameplay. That should be a separate issue (and probably much more feasible in the `resource_files` branch.

**Comment by bcahue** [comment]
The actual supporting of widescreen assets has been merged but it seems the whitelist implementation to support "trusted" clientside WADs may be a different feature, so I will close this and create a new one based on that idea.
