### ISSUE TITLE
[BUG] Volume sliders are broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by ghost** [odamex/odamex#333]
**Describe the bug**
This bug occurs whenever user tries to change the volume levels (applies to music, sound and announcer volumes). The slider gets permanently stuck at 0% percent volume level and to fix this you have to purge the configuration files. 

**Build that the bug occurred in**
Odamex v0.9.0 (g1b2a9-6690)

**To Reproduce**
Run Odamex for the first time (without the configuration files on the system). Then try to lower the volume.

**Expected behavior**
Actually changeable sound and music volumes.

**Screenshots, NetDemos, & Crash Dumps**
[bug.zip](https://github.com/odamex/odamex/files/6401660/bug.zip)

**Additional context**
Checked system for faulty packages, but it looks like everything is alright. The system is updated to the latest available version possible. Nothing is failing during compilation time. Tried to switch the graphics servers/protocols from Wayland to X11 and vice versa, but still the game won't budge.

Operating system in question is Ubuntu 20.04 LTS.

**Comment by bcahue** [comment]
I can't reproduce this on Ubuntu 22.04 LTS -- the sliders operate as normal.

https://github.com/user-attachments/assets/afe911fa-1a26-4095-8ff2-900ed9ba6cb9

Video attached. Please refile with more information if you still experience this bug.
