### ISSUE TITLE
[FEATURE] Disable Chat Sounds

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#338]
**Is your feature request related to a problem? Please describe.**
Streamer requesting ability to mute chat sounds, but keep text on screen.

**Describe the solution you'd like to see**
Add a cvar and add a "Chat Sounds" On/Off in the menu. Alternatively, add a separate sound slider for it in the same menu and just have the on/off switch set it to 0.

**Comment by Ch0wW** [comment]
Feature was merged with the latest stable build, can you test to make sure it does what you wanted?
![image](https://user-images.githubusercontent.com/2938006/117813266-26f48e80-b263-11eb-87ee-0a8feec149f9.png)

**Comment by leximayfield** [comment]
Released as part of 0.9.1.
