### ISSUE TITLE
[BUG] Client crash on connect

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#341]
**Describe the bug**
Client crashed while connecting.

**Build that the bug occurred in**
0.9 Stable

**To Reproduce**
Cannot reliably reproduce.

**Screenshots, NetDemos, & Crash Dumps**
Crash dump attached.

[odamex_g749b6_13268_20210504T232827.zip](https://github.com/odamex/odamex/files/6424414/odamex_g749b6_13268_20210504T232827.zip)

**Comment by leximayfield** [comment]
Near as I can tell, this is a MIDI crash.

> Unhandled exception at 0x00007FFCEE723799 (midimap.dll) in odamex_g749b6_13268_20210504T232827.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by rakohus** [comment]
Bug #396 duplicate was closed. Was run with -nomusic. Is midi subsystem still active when -nomusic param is passed?

**Comment by rakohus** [comment]
**[General conditions]**
•On wdl2021.wad, which uses mod/xm/ogg music

**[When does it crash?]**
•When using the `-connect` cmdline param passed through launcher
•When music system backend is portmidi
•When `-nomusic` is passed, if portmidi is music system

**[When does it not crash?]**
•When launching client and connecting through console, regardless of music system backend
•When music system backend is sdl mixer
•When music system is set to no music
•When `-nosound` is passed

**Comment by rakohus** [comment]
Will repost in the future if it turns up again. Been quiet on this front for a bit.
