### ISSUE TITLE
[FEATURE] Client SR50 Bind

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#342]
**Is your feature request related to a problem? Please describe.**
A "sr50" bind has been going around for over a decade. Many players use it - others are unaware of its existence. If we're going to allow it, it's time to at least consider adding it to the engine officially. We should have a discussion about this.

**Additional context**
How the bind typically works:

```
alias "+left2" "+left\;+moveleft"
alias "+right2" "+right\;+moveright"
alias "+sr" "turnspeeds 65536\;+strafe"
alias "-left2" "-left\;-moveleft"
alias "-right2" "-right\;-moveright"
alias "-sr" "turnspeeds 0\;-strafe"
```

**Comment by leximayfield** [comment]
I have no dog in this fight on if it should be added or not.  I'm fine with whatever the consensus lands on.

**Comment by rakohus** [comment]
Given there has been no discourse regarding this in 2.5 months, I recommend we consider moving forward with implementing this - potentially for Oda 10.

**Comment by Ru5tK1ng** [comment]
This would be the first for any doom port (that I know of) to implement a bind for sr-50. I don't really see any issue with it considering sr-50 isn't a cheat and since over 90% of competitive players use aliases anyway. Cutting out the middle man and adding a bind for it simplifies things for the better.

**Comment by rakohus** [comment]
Support for this has been added in the sr50 branch with commit d8e7584. Not merged into protobreak yet, but we seem agreed that it's going to come in as a cvar that simply adds the behavior to +strafe. It is on by default, but can be toggled off.

**Comment by rakohus** [comment]
Introduced in Odamex 10.
