### ISSUE TITLE
[BUG] Dehacked Starting Player Health Ignored by Server

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#345]
**Describe the bug**
In 0.9.1 builds, dehacked starting health seems to be ignored. This worked in 0.9 stable.

**Build that the bug occurred in**
discon-debug (g6859-6720)

**To Reproduce**
Can be seen in the `[WDL] Odamex Development Branch Test Server - Super Rocket Arena Turbo` on `rkt_a2.wad`. Health resets to 100, breaking intended behavior.

**Expected behavior**
Observe dehacked starting health at all times, including after a new round begins.

**Comment by leximayfield** [comment]
#348 I believe fixes this.

**Comment by rakohus** [comment]
PR #348 fixed this issue. Thanks @AlexMax
