### ISSUE TITLE
Remove vanilla demo recording support 

### ISSUE THREAD

**Issue by Ch0wW** [odamex/odamex#346]
**Describe the bug**
Odamex supports demoplayback in a very good way, as 9 demos out of 10 can be playbacked without any major issues or desynchronization.

However, recording a vanilla demo gives way more problems than imagined, with many possible cases of desyncs due to how Odamex handles a few commands/physics/CVARs. Since it's definitely not 100% vanilla-capable and definitely unusable by speedrunners, I don't see why we should keep it any longer.

**Build that the bug occurred in**
Any since vanilla demorecording was introduced.

**Comment by rakohus** [comment]
Which cvars would cause a typical desync? I believe the mouse code might cause issues. Requesting more information to support this action.

**Comment by Ch0wW** [comment]
Any latched CVARs aren't entirely taken into consideration when using a vanilla record (`sv_skill` is the best example of it), although this is a deeper issue with how we handle latched cvars, both clientside and serverside.

**Comment by Ch0wW** [comment]
A PR was merged fixing this issue, feel free to reopen if something went wrong.
