### ISSUE TITLE
[FEATURE] Team Obituaries

### ISSUE THREAD

**Issue by denzoa** [odamex/odamex#367]
Team based obituaries: each player gets a color unique to that team. (I.e. blue, red, green,...)

It would look like this in the onituaries;

(Blue text) Denzoa (default text color) was splattered by (blue text) AlexMax’s (default text color) supershotgun !

**Comment by rakohus** [comment]
This is actually accomplished with the new obituary kill feed introduced in Odamex 10. Marking closed as it will be in the upcoming release! Thanks for the suggestion @denzoa
