### ISSUE TITLE
[BUG] Client requires restart to enable 32-bit color

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#370]
**Describe the bug**
If you start in 32-bit color, then change to 8-bit color, Odamex will not reset back to 32-bit color if you set it back. The client will require a restart.

**Build that the bug occurred in**
0.9.1 tagged release.

**To Reproduce**
Start in 32-bit color. Use the video menu or cvar to change to 8-bit color, then attempt to revert back. Nothing will happen and you will be stuck in 8bpp.

**Expected behavior**
Video should be reinitialized with 32bpp.

**Screenshots, NetDemos, & Crash Dumps**
If applicable, add screenshots, NetDemos, or crash dumps to help explain your problem.

**Additional context**
Bug has been present since 0.8.

**Comment by bcahue** [comment]
Tried to reproduce this today and could not. I was able to change renderer color depth in full screen windowed, windowed and full screen exclusive. Can you provide steps on how to reproduce this?

**Comment by cuantar** [comment]
Could not reproduce this.

**Comment by rakohus** [comment]
Even I can't reproduce it anymore. Closing. Thanks for checking in on this
