### ISSUE TITLE
[BUG] Nintendo Switch builds stays on a black screen when exiting.

### ISSUE THREAD

**Issue by Ch0wW** [odamex/odamex#371]
**Describe the bug**
Odamex for the Nintendo Switch is unable to quit properly. It ~~either crashes (doesn't save the game), or~~ just quits into a black screen.

**Build that the bug occurred in**
Odamex 0.9.0 and onward.

**To Reproduce**
Just quit the game.

**Expected behavior**
It should exit properly to the Homebrew launcher.

**Additional context**
~~The crash may reside on the zone.clear(); function in Z_Close().~~

I've tried building a binary with nothing inside main() and the game still ends up with a black screen. So I'm truly lost on why it does that behaviour.

**EDIT:** First post updated.

**Comment by Ch0wW** [comment]
Testing with the zone-rework-fix, Odamex doesn't crash anymore when exiting. So that's one big issue fixed. 

However, it still ends on a black screen, and no return to the HBL other than quitting the game by force.

**Comment by rakohus** [comment]
@Ch0wW any update on this and do you foresee working on it in the near future?

**Comment by rakohus** [comment]
@Ch0wW checking in again for an update. Do you expect to continue work on your Switch port? If not, this bug may be closed out for now and can be re-opened if work continues.

**Comment by rakohus** [comment]
No feedback after multiple requests. Closing. Can be reopened at a later time if/when work continues in this area.
