### ISSUE TITLE
Eviternity messed up level 30

### ISSUE THREAD

**Issue by lemonzest79** [odamex/odamex#374]
Map 30 of eviternity.wad is all messed up, missing walls, floor, hom everywhere. Think its a MBF Format wad.

![Odamex_SOLO_20210522_075815](https://user-images.githubusercontent.com/40669977/119218177-f28c9800-bad6-11eb-8315-c86b99a040e6.png)
![Odamex_SOLO_20210522_075819](https://user-images.githubusercontent.com/40669977/119218179-f3bdc500-bad6-11eb-9ce9-f3a1530619b6.png)

In PrBoom-Plus the level has a wall that rises, then water fills in and the level looks what I assume is correct.

**Comment by Ch0wW** [comment]
Good find! I've currently checked the source, and there's a mistake in one ceiling function. Instead of lowering... It raised, making everything upside down. It's not totally fixed yet as textures are missing, but look at how it looks now.

![Odamex_SOLO_20210523_163855](https://user-images.githubusercontent.com/2938006/119265072-ac722a00-bbe5-11eb-929a-f0a5d128c545.png)

**Comment by lemonzest79** [comment]
Hey looking good :) There is also a floor that does not raise in one level and the player remains in a pit at the start, I'll get the level number in a bit

its level 13, I am assuming the floor is meant to rise up but it does not.

**Comment by Ch0wW** [comment]
This? Looks like it works just fine with that fix enabled. Unless it's another one?

EDIT: it was actually thanks to `co_boomphys` .

![Odamex_SOLO_20210523_165030](https://user-images.githubusercontent.com/2938006/119265432-032c3380-bbe7-11eb-9109-e14db15974d3.png)

**Comment by lemonzest79** [comment]
On the 0.9.1 build it does not raise, if it does work now with your fix that's great :)

**Comment by Ch0wW** [comment]
Excellent then! However, MAP30 still can't be finished as the boss immediately disappears after his waking up animation. 

I'll close this ticket once I'll both fix the floor texture and the missing boss frame.

**Comment by lemonzest79** [comment]
Great, thanks :)

**Comment by Ch0wW** [comment]
Missing floor textures corrected, result looks like this. I still have to figure out why the boss disappears (or doesn't even have waking sounds).

![Odamex_SOLO_20210523_180118](https://user-images.githubusercontent.com/2938006/119268696-6a9cb000-bbf4-11eb-800a-00fb28b4ec88.png)

**Comment by lemonzest79** [comment]
Used the exe given to me in discord and it builds the level as I presume it should, walls come down, water fills the level, I run around a bit and the walls then come down releasing a horde of monsters and I use god mode to kill them all, but after they are dead, a bfg is lowered and nothing happens.

**Comment by Ch0wW** [comment]
Pull Request #378 should take care of this issue.

**Comment by rakohus** [comment]
Just tested locally and online in Oda 10 dev builds. Was able to kill the final boss and everything seems to work fine, even with both of his final forms. Marking closed. Thanks for reporting @lemonzest79 and thanks to @Ch0wW and kblair for the work to make this run
