### ISSUE TITLE
[BUG] Cannot unbind non-keyboard inputs

### ISSUE THREAD

**Issue by Zddastan** [odamex/odamex#379]
**Describe the bug**
The "unbind" command doesn't affect any mouse button at all. Despite using this command multiple times on different mouse buttons (including side buttons), you cannot clear any mouse button of cvars if there is one assigned to it already.

**Build that the bug occurred in**
Odamex 0.9.1 (Build GC96C-1)

**To Reproduce**
Bind a command to any mouse button, then try to unbind it afterwards using the `unbind` command.

**Expected behavior**
I expected my middle mouse button to be clear of any cvar but that doesn't seem to be the case.

**Screenshots, NetDemos, & Crash Dumps**
![image](https://user-images.githubusercontent.com/84753774/119547104-9783cb00-bd8c-11eb-9f60-4dd8b1c4f473.png)

**Additional context**
You can use (bind mousex "") as a workaround, but the unbind command is broken.

**Comment by Ch0wW** [comment]
In fact, any key other than a-z will have that issue, not only the mouse.

**Comment by Ch0wW** [comment]
Issue found, will issue a PR in the next few minutes.

**Comment by rakohus** [comment]
Gave binaries to Dastan and he confirmed the fix. I also tested as well. Thanks Ch0ww!
