### ISSUE TITLE
[BUG] Odamex detecting AltGr as a chat macro

### ISSUE THREAD

**Issue by Zddastan** [odamex/odamex#380]
**Describe the bug**
Whenever you press AltGr (in AZERTY keyboards) + 0-9 after opening the chat, it erases my whole sentence and replaces it with the Doom chat macros.

**Build that the bug occurred in**
Odamex 0.9.1 (Build GC96C-1) _(and earlier down to 0.8.x)_

**To Reproduce**
_-For AZERTY/Other keyboards that have the AltGr key_: open the chat then press AltGr + 0-9
_-For QWERTY keyboards_: open the chat then press Ctrl+Alt (look at _Additional Context_ for more explanation) + 0-9

**Expected behavior**
Since this button is used as a shortcut for special characters, I was expecting it to type out a character corresponding to its position between 0-9 (~ # { [ | ` \ ^ @).

**Screenshots, NetDemos, & Crash Dumps**
https://user-images.githubusercontent.com/84753774/119567150-dc672c00-bda3-11eb-9799-d4e319e70753.mp4

 **__Notes:__** Since the keyboard overlay shows characters instead, here are the corresponding numbers:
_& = 1_ / _é = 2_ / _" = 3_ / _' = 4_ / _( = 5_ / _- = 6_ / _è = 7_ / _ = 8 / _ç = 9_ / _à = 0_

**Additional context**
After running a keyboard overlay, I noticed that the AltGr key is actually a shortcut for Ctrl+Alt. So you might be able to replicate this issue on QWERTY keyboards with those two keys.

**Comment by rakohus** [comment]
Thank you for the video, this will be helpful. Seems like Odamex client is probably just seeing the Alt press and moving forward with the alt+number macros from Doom.

**Comment by rakohus** [comment]
Thanks @bcahue
