### ISSUE TITLE
[FEATURE] Notify old clients to go to Odamex website

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#384]
**Is your feature request related to a problem? Please describe.**
Currently, the client does not instruct players to go to Odamex.net if they have an old client. It just says that they have an out-of-date client.

**Describe the solution you'd like to see**
Notify old client to go to Odamex.net for a new client.

**Additional context**
![image](https://user-images.githubusercontent.com/22926877/120092305-e8bef200-c0df-11eb-9529-1454ed9e20e2.png)

**Comment by leximayfield** [comment]
I believe this was fixed sometime during development of protobufs.

https://github.com/odamex/odamex/blob/protobreak/common/version.cpp#L103

**Comment by rakohus** [comment]
It was fixed. Tested in Oda 10. Fixed
