### ISSUE TITLE
[BUG] Players disappear after other clients think they have died

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#393]
**Describe the bug**
Players disappear after other clients think they have died. If you F12 the player that goes invisible, their health will drop to 0 and soon after their body's point of view will become disassociated with their true position.

**Build that the bug occurred in**
0.9.2

**To Reproduce**
Unknown, but demo is attached.

**Expected behavior**
Player health reported correctly - not disappear.

**Screenshots, NetDemos, & Crash Dumps**
[Odamex_CTF_20210601_204227_WDL2021N.WAD_MAP25.odd.zip](https://github.com/odamex/odamex/files/6581419/Odamex_CTF_20210601_204227_WDL2021N.WAD_MAP25.odd.zip)

**Additional context**
Behavior occurs at 8/8 41:44. 41:42. He has 5 HP.  Seneca walks over two stimpacks - no health added, then shot and dies

**Comment by rakohus** [comment]
41:42. He has 5 HP. Walks over two stimpacks - no health added

**Comment by leximayfield** [comment]
For the record, the ghost player in this demo is Seneca.

**Comment by rakohus** [comment]
Seems to have been resolved by #397. Thanks Alex
