### ISSUE TITLE
[BUG] Client disconnected while the server changed map.

### ISSUE THREAD

**Issue by Star-Prince** [odamex/odamex#394]
When changing map, Odamex disconnected from the server.

-Build that the bug occurred in-
0.9.2

-To Reproduce-
Error occured while changing to UDMX map08.
TODO: Find out if changing to UDMX map08 always causes this.

-Expected behavior-
Client changes to the new map and doesn't disconnect from server.

-Screenshots, NetDemos, & Crash Dumps-
![oda_udmx_error](https://user-images.githubusercontent.com/49964766/120708281-604aa380-c489-11eb-87df-f68abe36e0ea.png)
TODO: Find the netdemo and find the crash dump if one was created.

-Additional context-
I was running the client on Linux (Manjaro) using a client I built from the
Odamex GitHub repository (not the AUR version).

**Comment by rakohus** [comment]
@Star-Prince were you ever able to follow up on seeing if this was reproduceable?

**Comment by rakohus** [comment]
A lot of netcode has changed and no response in over a month. Can re-open a new issue if this pops up again. Thanks for the initial report @Star-Prince.
