### ISSUE TITLE
[FEATURE] Make the installer check if VS Redistribuables are installed

### ISSUE THREAD

**Issue by Ch0wW** [odamex/odamex#400]
**Is your feature request related to a problem? Please describe.**
On Windows, Odamex **REQUIRES** the VS Redistribuables to be installed to run the launcher properly.
However, a very common issue from users I've noticed is that those redistribuables aren't necessarily installed.

**Describe the solution you'd like to see**
On the installer, make sure the installer can see those files. If not found, point them to the website, according to their architecture.

I believe https://stackoverflow.com/questions/10982468/innosetup-check-if-visual-studio-2010-crt-redist-is-installed-if-not-then-run can be very helpful solution for that.

**Describe alternatives you've considered**
In the meantime, remind users to download these, if these aren't installed, at least in the FAQ.

**Comment by rakohus** [comment]
Are we able to statically link these DLL files on release builds? @AlexMax

**Comment by bcahue** [comment]
Completed.
