### ISSUE TITLE
[FEATURE] mute_spectators also blocking spectator teamchat

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#401]
**Is your feature request related to a problem? Please describe.**
With mute_spectators enabled, while regular chat from spectators is disabled, spectators will still see spectator teamchat.

**Describe the solution you'd like to see**
Block spectator teamchat in the same manner it blocks allchat from spectators

**Describe alternatives you've considered**
Turning off all messages during the game, which sucks, because it wipes all other info like CTF info and obituaries. If I had to do that it would suck a lot for live broadcasts of the World Doom League.

**Additional context**
None available.

**Comment by Ch0wW** [comment]
Good catch. I'll provide a fix later on.

**Comment by Ch0wW** [comment]
https://github.com/odamex/odamex/pull/402 should take care of the issue.

**Comment by rakohus** [comment]
Tested fix in #402. Confirmed.
