### ISSUE TITLE
[BUG] UMAPINFO Maps do not progress

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#414]
**Describe the bug**
Maps in UMAPINFO branch do not advance correctly. Occurs in client and server. Easily viewable in Sunlust

**Build that the bug occurred in**
bug/umapinfo-fixes 1c57866

**To Reproduce**
Play through sunlust map01. It will loop back.

**Expected behavior**
Advance to next map.

**Additional Info**
Tagging @DeathEgg

**Comment by leximayfield** [comment]
Fixed by 0b31888 - for some reason the map lump was being treated differently depending on if it was a quoted string or not, which is not accurate to how GZDoom handles it.

**Comment by rakohus** [comment]
Tested. Confirmed fixed in 0b31888. Thanks @AlexMax
