### ISSUE TITLE
[FEATURE] Broadcast level completion time in console on Coop modes

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#416]
**Is your feature request related to a problem? Please describe.**
Potential for coop speedrunning. .

**Describe the solution you'd like to see**
Broadcast level completion time in console after exit is reached. Take "rounds" into account for survival modes so that the winning round time is displayed and not total time in the map

**Comment by leximayfield** [comment]
I've been thinking about this and you'd also have to draw a distinction between pistol-starting and carrying over an inventory from a previous level, because you can probably get a faster time with a BFG than without.

**Comment by rakohus** [comment]
Addressed in PR #477. Thanks Alex!
