### ISSUE TITLE
[FEATURE] Ability for server to end warmup and start a game for events

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#425]
**Is your feature request related to a problem? Please describe.**
Event management. If there are a very large number of players in a game for an event, it would be nice if you can stick them into the warmup mode and manually activate it from the server to begin the event.

**Describe the solution you'd like to see**
Server ccmd? 

**Additional context**
Open to discussion on how to best manage a server with many players (e.g. 50+)

**Comment by Ch0wW** [comment]
Seems extremely easy to implement with a server CCMD (`forceready`). In that meantime, the ratio required for a game to start should be set to 1.0 .

Other than doing that change in the config, I'm fine with it.

**Comment by rakohus** [comment]
Bad request. This already exists. The server can use the `forcestart` server console command. Hooray!
