### ISSUE TITLE
[BUG] Dehacked Monster causing Crash

### ISSUE THREAD

**Issue by katarn11** [odamex/odamex#429]
**Describe the bug**
Running Dimensions of the Boom wad (https://www.moddb.com/mods/dimension-of-the-boomed/downloads/dimension-of-the-boomed-vanilla-boom) the dehacked monster "scrag" which is a replacement for the lamp "thing" crashes Odamex when you shoot it. Occurring in Odamex 0.9.3 - Warp to map03 as there is a scrag immediately around a corner; on most computers the first one you shoot will crash; however in the video I recorded on a separate machine it happened when the second one was encountered.

Here is a video recording https://youtu.be/0KezyCUtCH0

While I run the MacOS version; this happened to another player on running Windows at the same spot.

**Comment by Ch0wW** [comment]
Pull Request #403 doesn't seem to trigger the issue even after many saves and loads.

Can you manually fork and compile that branch to verify?

**Comment by rakohus** [comment]
Tested this in newest dev builds. This wad has some other issues online re: polyobjects but the scrag doesn't crash the game. Tested locally and online. Marking closed. Thanks for report @katarn11
