### ISSUE TITLE
[BUG] Monster remains "alive" on client, but dead on server

### ISSUE THREAD

**Issue by SpaikouZanclouver** [odamex/odamex#431]
**Describe the bug**
Encountered an Invincible Pinky
This pinky was wandering around and i decided to fist it
then i noticed im not taking damage despite its attack animation was playing
another player told me he had experienced the same but i wasnt sure if he encountered it the same time or earlier
Could be a case of Bad Packet like in zdaemon except it can wander around

**Build that the bug occurred in**
Version 0.9.3

**To Reproduce**
it was unexpected and might happen again in the future

**Screenshots, NetDemos, & Crash Dumps**
wish i could see it again and provide a screenshot next time

**Additional context**
i was in the romero sigil coop server

**Comment by rakohus** [comment]
This is a known bug in the current netcode (0.9.3) where a desync occurs between the server and the client. Typically, the monster has died on the server but the client misses the server message telling the client to kill the monster. The client then continues to show the monster, but the monster does not actually exist on the server. Our next major version includes a rewrite in how messages are sent from the server to the client, which will make deciding on the most viable fix for this issue much easier.

**Comment by rakohus** [comment]
Editing the bug description

**Comment by rakohus** [comment]
Thanks for the report @SpaikouZanclouver! Our monster netcode has changed and this behavior may be different for the impending Odamex 10.0.0 release. Please re-report or comment on this bug if you see this happen again on the new version. Closing for now.

**Comment by hjri** [comment]
I've seen it happen on Odamex v10.4.0 (HEAD, g46e0e1-8728), playing with a friend from half a globe away (300ms ping), he said it was quite common occurrence for he constantly had to double-check whether enemy is real or not. I've seen it happen myself but only once (5-20ms ping)
