### ISSUE TITLE
[BUG] The client crashes with segmentation fault error

### ISSUE THREAD

**Issue by ghost** [odamex/odamex#434]
**Describe the bug**
The client crashed unexpectedly during the John Romero's deathmatch session that took place on July 16th, 2021. It looks like something happened with the server itself (a server crash?) and it caused most of the clients to crash simultaneously.

**Build that the bug occurred in**
0.9.3

**To Reproduce**
Simulate a server crash.

**Expected behavior**
The game itself.

**Screenshots, NetDemos, & Crash Dumps**
[odamex_g2dbdb_63032_20210716T213254_dump.txt](https://github.com/odamex/odamex/files/6833026/odamex_g2dbdb_63032_20210716T213254_dump.txt)

**Additional context**
 The WAD in question is DOOM2.WAD.

**Comment by rakohus** [comment]
Threw this bug out in the dev channel and @bcahue believes this bug was fixed in the MBF21 branch coming into Odamex 10. He threw up some evidence so let's hope he's right. I'll mark this closed for now. We can re-open in the future if the same bug shows back up. Thanks for the report @SapientLion!
