### ISSUE TITLE
[BUG] Silent teleporter line 208 broken

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#444]
**Describe the bug**
Doom Silent Teleporter line action 208 was broken in PR #320.

**Build that the bug occurred in**
4b50f0f

**To Reproduce**
Lazarus1k.wad Map08. BFG hall.

**Comment by leximayfield** [comment]
Please check branch `bug/fix-208`.  I've tested on a test map and on lazarus, plus checked map30 to ensure we didn't have any regressions.
