### ISSUE TITLE
ZMAPINFO Error

### ISSUE THREAD

**Issue by ericabxy** [odamex/odamex#453]
Using Odamex 0.9.3 on Ubuntu raises a ZMAPINFO error when loading kneedeep.wad. The error does NOT raise using Odamex 0.8.3. Since Odamex behaved as expected in 0.8.3 but not in 0.9.3 I'm assuming this is a bug introduced after 0.8.3

`ZMAPINFO:9: Script Error: Expected '=', got '}'.`

Looking in the ZMAPINFO lump for the WAD I found the offending line. The key compat_nopassover does not assign a value; likely because it is intended as a boolean that defaults to False.

`map MAP01 "bury my heart knee deep"
{
	levelnum = 01
	titlepatch = CWILV00
	next = MAP02
	sky1 = SKY1
	music = "D_RUNNIN"
	compat_nopassover
}
`
[link to Kneedeep WAD](https://www.doomworld.com/idgames/levels/doom2/j-l/kneedeep)

**Comment by bcahue** [comment]
Tested and confirmed the error exists with 0.9.5, but is fixed with the branch protobuf-baseline (tested commit 024d666).

**Comment by rakohus** [comment]
Tested in newest `protobreak` on commit `f5b6c8d`. Will be in next major release. Closing as fixed!
