### ISSUE TITLE
[BUG] Odamex crashes; locks up entire system

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#455]
**Describe the bug**
Multiple players have experienced this (including me). Sometimes the client will hard lock the entire system. Hard, physical reboot is required.

**Build that the bug occurred in**
0.9.3+

**To Reproduce**
Unknown. No crash dump is produced. Unknown how to record this event.

**Comment by rakohus** [comment]
Things to track going forward when players experience this:

- What video mode do you play in? (Windowed, Window Fullscreen, FS Exclusive)
- Does ctrl+alt+del, win+L, or ctrl+shift+esc do anything?
- Did your sound freeze?
- Did you have music on/off? What was the music system set to?

**Comment by rakohus** [comment]
On a new pc. Felt a similar phenomenon, but it eventually crashed. Possibly related. Dump attached. Base 0.9.4 build.
[odamex_g9033_5608_20210828T220102.zip](https://github.com/odamex/odamex/files/7071562/odamex_g9033_5608_20210828T220102.zip)

**Comment by leximayfield** [comment]
This PDB could not be loaded because it was made with the initial 0.9.4 release that we took down because of a last-minute bug.  If you can replicate this on 0.9.5 stable, that would be really useful.

**Comment by rakohus** [comment]
Closing for now. Haven't seen it again recently. Will open new bug if new information is obtained.
