### ISSUE TITLE
[FEATURE] Add Rekkr as a recognized iwad

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#457]
**Describe the solution you'd like to see**
Add Rekkr to DoomIWadNames

**Comment by Ch0wW** [comment]
We're talking about the standalone one, right?

**Comment by rakohus** [comment]
I'm talking about any version of Rekkr which is an iwad, which is all of them as far as I know. Does the standalone version have a different wad name? Functionally, Odamex should treat them the same as far as I know

**Comment by Ch0wW** [comment]
One is a PWAD, the other is an IWAD. Both are also used.

Hence the question.

**Comment by leximayfield** [comment]
Looking at their site, it appears to me that the REKKR IWAD is a contrivance for being distributed by itself with Chocolate Doom, and that the intended method of play with an arbitrary source port is to simply load it as a PWAD alongside Ultimate Doom or Freedoom.

We could recognize Rekkr as a recognized IWAD, but what exactly would that buy us?

**Comment by rakohus** [comment]
Rekkr is sold as an independent game on Steam. That's more than we can say for other IWADs we support, like Hacx. I am of the mind that, because of its recently minted independent game status (where it is packaged as an IWAD), it's another easy feather in our cap.
![image](https://user-images.githubusercontent.com/22926877/147834809-0dca2544-1407-49fc-bb1a-e04274019bc9.png)
![image](https://user-images.githubusercontent.com/22926877/147834827-ace49841-d9f2-463a-b238-1662ab9c4826.png)

**Comment by leximayfield** [comment]
Added preliminary support for the 1.16a IWAD in 9be02db.  Seems to work, mostly, except I didn't notice map names below ENTERING. Still, would like to get more eyes on it.

**Comment by rakohus** [comment]
Everything looks good sans the entering graphic not showing, as @AlexMax noted above.

**Comment by rakohus** [comment]
Entering graphic not appearing is not a REKKR specific issue. Marking as closed. Thanks @AlexMax
