### ISSUE TITLE
[FEATURE] allow .bex files to be loaded with a -bex command line

### ISSUE THREAD

**Issue by lemonzest79** [odamex/odamex#462]
**Is your feature request related to a problem? Please describe.**

Hi

Could a command line argument of -bex to load dehacked patches be added please?, it is in both zdoom and zdaemon, the launcher I'm using called Doom Runner loads bex/deh files with a corresponding -deh/-bex command line so while both of the other ports respect this command line odamex does not and fails to load the bex patch, it would be nice for a little consistency between ports  instead of having to rename all my .bex files to .deh

**Describe the solution you'd like to see**

A command line argument to load bex files with -bex
**Describe alternatives you've considered**

going through my wad collection and rename .bex files to .deh

**Additional context**

**Comment by lemonzest79** [comment]
Just checked Zandronum can also load .bex files with -bex

**Comment by Ch0wW** [comment]
Why not using the `wad` command instead? It should be able to load .deh/.bex files.

**Comment by lemonzest79** [comment]
https://github.com/Youda008/DoomRunner/releases

This is the ZDoom launcher, it does all the command line stuff automatically, based on file extension no way to override, zdoom/gzdoom/zdaemon/zadnroum all have the -bex command so as it is for zdoom deriviates it kinda expects the command line option to be there, is it hard to add to odamex? thanks for all your help.

**Comment by leximayfield** [comment]
Fixed in 3deadc6.
