### ISSUE TITLE
[FEATURE] Timed Spawn Protection

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#467]
**Is your feature request related to a problem? Please describe.**
Potentially useful for horde mode and other large, congested games. This has come up while testing Horde and a player spawns into an existing group of monsters once they come back to life in a later round.

**Describe the solution you'd like to see**
A Skulltag-style spawn protection that is activated and operated via a timer.

Proposed CVAR: `sv_spawnprotectiontime`

CVAR Function:
- If 0, feature is disabled.
- If > 0, n = spawn protection in seconds
- Player is invulnerable for n seconds. There should be a visual indicator to denote the temporary invincibility, both to local player and other actors. Skulltag used flashing hud/player sprites. Could potentially use a "tint" on the hud weapon and actor sprite ala horde bosses. 

**Describe alternatives you've considered**
Hardcode the spawn protection time and make it a bool instead of an int. Less flexibility but easier for users to understand. Could then use a shorter name like `sv_spawnprotection`. Probably not the best solution as the protection time, for instance in horde vs lms, might reasonably warrant different times.

**Comment by leximayfield** [comment]
#473 adds this as part of spawn inventory.

**Comment by rakohus** [comment]
It does, but the issue of a visual indicator was not addressed. Is this something we are deciding to forego?

**Comment by leximayfield** [comment]
At some point in the past, I thought that the screen would flash like running out of an invul sphere.  If this doesn't happen, that's a bug.
