### ISSUE TITLE
[FEATURE] Weapon Pickup Message Toggle

### ISSUE THREAD

**Issue by OpenRift412** [odamex/odamex#468]
In vanilla Doom's multiplayer, there is no message shown when picking up a new weapon (both in coop and DM). In Odamex however, weapon pickup notifications are enabled along with all other item pickups. Could we perhaps get a toggle that can enable/disable weapon pickup messages separately?

**Comment by Ch0wW** [comment]
There's already an option to do so :)
![image](https://user-images.githubusercontent.com/2938006/135350214-c2a90485-fedf-4f3c-aa48-6717fcd2fe88.png)

**Comment by rakohus** [comment]
@Ch0wW this does not address the request. In vanilla, weapon pickups do not receive any message in netplay. This can be verified through chocolate doom by running the `-solo-net` cmd line param. I'm not sure if it is worth adding the toggle for this, but right now weapon pickups are lumped with the rest of the item pickups, as explained in @OpenRift412's request. Absent someone submitting a patch, it will be considered.

**Comment by Ch0wW** [comment]
I understand, but I don't see the need to "unfix" a super minor bug that's in vanilla that can "negatively" impact gameplay. 

**WON'T FIX** for me. It'd be a big waste of time (and an additional CVAR) to vanilla-ize this thing only for 1 person.

https://doomwiki.org/wiki/Weapon_pickup_message_not_displayed_in_multiplayer is the bug description from the wiki btw.

**Comment by rakohus** [comment]
Discussed amongst the development team. Thanks for bringing it to our attention but the consensus seems to be that, although it would be "vanilla correct", it is a trivial change and does not bring value to the engine. Won't implement
