### ISSUE TITLE
[PISTOL START] cvar or argv swith for pistol start

### ISSUE THREAD

**Issue by runlow** [odamex/odamex#479]
**Is your feature request related to a problem? Please describe.**
I'd challenge myself to play a wad with pistol start. I'd remember to restart the map but sometimes would realise half-way through the level that I forgot to do it or wouldn't be sure if I did. Would be nice if there was a way to force it.

**Describe the solution you'd like to see**
Either:
* `-pistolstart` command line switch
* some cvar maybe `sv_pistolstart`
* quick and dirty patch that I could apply that creates this behaviour

It has to work in single-player!

**Describe alternatives you've considered**
`IDCLEV` cheat
binding level restart to a key
different sourceport

**Additional context**
Same issue as this one, but on a different sourceport:
https://github.com/coelckers/prboom-plus/issues/132

**Comment by runlow** [comment]
for now this is working for me
```diff
--- a/client/src/cl_level.cpp
+++ b/client/src/cl_level.cpp
@@ -538,5 +538,4 @@ void G_DoLoadLevel (int position)
                if (it->ingame())
                {
-                       if (it->playerstate == PST_REBORN)
                                it->doreborn = true;
                        it->playerstate = PST_ENTER;
```

**Comment by leximayfield** [comment]
I like this idea.  I imagine it will be a pistol start cvar that acts a bit like skill in that it doesn't save between games.
