### ISSUE TITLE
[FEATURE] Projectile passthrough flag for allies

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#484]
**Is your feature request related to a problem? Please describe.**
Only a problem if there are a large amount of players jammed into a coop map or mode.

**Describe the solution you'd like to see**
A svar that allows for projectiles to clip through players so direct impacts aren't possible.

**Describe alternatives you've considered**
Not adding an option for server owners to enable for large crowded servers might be negatively impactful to the player experience in some maps and mods where rockets, for example, are prevalent.

**Additional context**
None, I want people to be able to jump in and play and enjoy even in servers slam full of monsters and players. Accessibility options help with this.

**Comment by bcahue** [comment]
This can be added to the same functionality that handles sv_unblockplayers for projectiles as well as players trying to pass thru one another. I will submit a pull request for this to add teams checking for sv_unblockplayers projectiles and explode accordingly.

**Comment by leximayfield** [comment]
Merged a feature for this.
