### ISSUE TITLE
[BUG] Array tokens not being assigned correctly in ACS

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#489]
**Describe the bug**
Setting some array values evidently do not either get assigned correctly or overwrite other array values.

**Build that the bug occurred in**
0.9.5 (g4183-6903)

**To Reproduce**
Create a script with array and print values to reflect assignments in console, or just run attached file in multiple ports

**Expected behavior**
Arrays playing nice!!!!

**Screenshots, NetDemos, & Crash Dumps**
Attached screenshot shows the arrays going all wacky

**Additional context**
Tested and returned expected results in Zandronum 3.1 and GZDoom 4.6.0
[odamex_array_test.zip](https://github.com/odamex/odamex/files/7700046/odamex_array_test.zip)
![Odamex_SOLO_20211212_150006](https://user-images.githubusercontent.com/21268474/145733378-19de0db6-2171-4e74-997b-5ec6f711045b.png)

**Comment by rakohus** [comment]
Was this tested only on the client? For anyone that attempts to address this bug, it's worth considering that the server/client will need to intelligently sync this logic and know when to leave it up to the server.

**Comment by Xenaero** [comment]
Yes, it was only attempted client-side, singleplayer.

**Comment by bcahue** [comment]
Seems to be fixed now in `stable`, thank you @electricbrass!

![image](https://github.com/user-attachments/assets/bb848ef2-03be-4f66-8311-a0af93255215)
