### ISSUE TITLE
[BUG] Reset armor variant once current armor hits 0%

### ISSUE THREAD

**Issue by thefatwilly** [odamex/odamex#496]
Odamex currently remembers the previous armor a player has. When a player with 200% blue armor reaches 0% and then picks up an armor bonus then that becomes 1% blue armor.

In Vanilla behavior, the armor bonus should grant 1% green armor even if the last armor picked up was a blue armor.

**Comment by leximayfield** [comment]
To be clear, this is only a problem online, and only a visual problem - on the server you do in fact have green armor, it just looks blue.  Worth fixing, but not a problem in the playsim.

**Comment by leximayfield** [comment]
Should be fixed now.

**Comment by rakohus** [comment]
Tested in Odamex 10 release build. Confirmed and closing as fixed.
