### ISSUE TITLE
[FEATURE] Remove Demo Bar when HUD is maximized/gone

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#515]
**Is your feature request related to a problem? Please describe.**
Requesting demo playback bar be included with the rest of the hud elements removed when the hud is at max size

**Describe the solution you'd like to see**
Demo playback bar vanishes from detection by my eyeballs when I hit the + key a few times

**Describe alternatives you've considered**
Turning off the demo playback bar via a bind and I don't like that solution

**Additional context**
I like making things easier on everyone

**Comment by rakohus** [comment]
PR #589 merged. Thanks @Ru5tK1ng
