### ISSUE TITLE
[BUG] Player Z-Heights/positioning warp in Odamex 10 Dev Builds

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#521]
**Describe the bug**
Other players z-heights jump around.  They might be correcting to z-height of 0 when they cross, then snap back to real position. Easily seen on the top paths of WDL2021 Map01.

**Build that the bug occurred in**
9beo0

**To Reproduce**
Happens while playing on WDL2021.wad Map01. Seems that players will "snap" to z-height of 0 for a tic or two until it is corrected

**Expected behavior**
Players stay at their correct height

**Screenshots, NetDemos, & Crash Dumps**
Demo from Xenaero below. Observable around 3:57
[player_zheight_clipping_4m20s_wdl.zip](https://github.com/odamex/odamex/files/7919880/player_zheight_clipping_4m20s_wdl.zip)

**Additional context**
It seems this issue was probably introduced with `baseline` branch. Possibly related to state changes?

**Comment by leximayfield** [comment]
Please check this ⬆️ commit to see if you still see the issue.  I did some testing in a DM level and it looked okay, but it might still happen, and it's more difficult to test solo.

**Comment by rakohus** [comment]
Fixed in bca4442. Thanks @AlexMax!
