### ISSUE TITLE
[BUG] Valiant Map07 ends immediately after load

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#522]
**Describe the bug**
Valiant.wad map07 ends a couple moments after spawning in.

**Build that the bug occurred in**
Occurs in 0.9.5 and current Odamex 10 Dev builds

**To Reproduce**
Load valiant.wad. Console `map map07`.

**Comment by rakohus** [comment]
According to @DeathEgg, what's happening here is voodoo doll are spawning directly on barrels, causing them to immediately explode and kill the player and romero head. This ends the level.

Also affects map13.

**Comment by rakohus** [comment]
Our behavior differs from vanilla doom. What is happening is that a voodoo doll is spawned on top of a cluster of barrels with a romero head in the center. In vanilla doom, the voodoo doll will simply spawn inside the barrel and wait. Eventually, a ceiling is lowered, crushing everything below, blowing up the barrels, and killing the romero head which causes the game to move into the next map.

In Odamex single player, the voodoo doll spawns on the barrels but causes them to immediately explode as though they're telefragged. This causes the romero head to die and the map to immediately end.

In Odamex multiplayer, the "avatar" stand-in for voodoo dolls do not trigger the barrels to explode. Therefore, this behavior only occurs offline.

[valexittest.zip](https://github.com/user-attachments/files/16322572/valexittest.zip)


A test wad is attached. In chocolate doom, you will spawn and be able to see the setup from Valiant Map07 in front of you. Currently in Odamex, the voodoo doll will immediately blow up and end the map.

Additional note: a single spawn point will also blow up the barrels. This isn't shown in the wad but was tested.

**Comment by electricbrass** [comment]
It looks like in P_SpawnPlayer, Odamex has the new player teleport to itself to telefrag anything in the spot. This is not the case in other ports. I'm not sure if simply removing this from the client would solve the problem without other side effects or not.

https://github.com/odamex/odamex/blob/3a3c9d09f9b1307de11bd0f2061c86af29c19a38/client/src/cl_mobj.cpp#L153-L154

It looks like it originates from when a single version of P_SpawnPlayer was shared by the client and server, leading me to believe this was introduced for multiplayer and likely doesn't need to be in the client version of the function.

**Comment by electricbrass** [comment]
Yea I'm pretty confident it can just be removed.

**Comment by bcahue** [comment]
Closing this as this has been fixed in `stable`:

![image](https://github.com/user-attachments/assets/47b44d58-7e20-4e88-a792-b94cb15c86c8)
