### ISSUE TITLE
[BUG] Doom 1 intermission screens don't immediately go to finale upon finishing last map of an episode

### ISSUE THREAD

**Issue by DeathEgg** [odamex/odamex#524]
**Describe the bug**
If you beat any episode in Doom/Ultimate Doom, the intermission screen will wait as if showing the name of the next level instead of immediately continuing to the next screen. This also has the side effect of showing a broken "You Are Here!" screen on E1-E3.

**Build that the bug occurred in**
Current protobreak.

**To Reproduce**
Beat any Doom/Ultimate Doom episode and continue to the next screen at intermission.

**Expected behavior**
Should immediately continue to the finale screen after clearing the statistics screen.

**Comment by rakohus** [comment]
Resolved in #523. Thanks @DeathEgg!
