### ISSUE TITLE
[BUG] common/i_crash_posix.cpp:34:10: fatal error: execinfo.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [odamex/odamex#533]
Attempting to build Odamex 0.9.5 against musl results in the following failure:

```
FAILED: client/CMakeFiles/odamex.dir/__/common/i_crash_posix.cpp.o 
/usr/bin/x86_64-gentoo-linux-musl-g++ -DCLIENT_APP -DINSTALL_BINDIR=\"bin\" -DINSTALL_DATADIR=\"share\" -DINSTALL_PREFIX=\"/usr\" -DUNIX -I/var/tmp/portage/games-engines/odamex-0.9.5/work/odamex-src-0.9.5/client/sdl -I/var/tmp/portage/games-engines/odamex-0.9.5/work/odamex-src-0.9.5/client/src -I/var/tmp/portage/games-engines/odamex-0.9.5/work/odamex-src-0.9.5/client/../libraries/textscreen -I/var/tmp/portage/games-engines/odamex-0.9.5/work/odamex-src-0.9.5/common/. -I/var/tmp/portage/games-engines/odamex-0.9.5/work/odamex-0.9.5_build/common -isystem /usr/include/SDL2 -isystem /var/tmp/portage/games-engines/odamex-0.9.5/work/odamex-0.9.5_build/libraries/local/include  -DNDEBUG -O2 -pipe -march=x86-64 -frecord-gcc-switches -fno-diagnostics-color -fmessage-length=0 -Wall -Wextra -fdiagnostics-color=always -Wduplicated-cond -Wduplicated-branches -Wrestrict -Wnull-dereference -Wuseless-cast -Wformat=2 -Wno-unused-parameter -std=gnu++98 -MD -MT client/CMakeFiles/odamex.dir/__/common/i_crash_posix.cpp.o -MF client/CMakeFiles/odamex.dir/__/common/i_crash_posix.cpp.o.d -o client/CMakeFiles/odamex.dir/__/common/i_crash_posix.cpp.o -c /var/tmp/portage/games-engines/odamex-0.9.5/work/odamex-src-0.9.5/common/i_crash_posix.cpp
/var/tmp/portage/games-engines/odamex-0.9.5/work/odamex-src-0.9.5/common/i_crash_posix.cpp:34:10: fatal error: execinfo.h: No such file or directory
   34 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

It looks like this sort of issue has come up in other projects as well: https://github.com/tlx/tlx/issues/36

**Comment by leximayfield** [comment]
I do not have a musl Linux machine handy, but what happens if you link against [libexecinfo](https://github.com/resslinux/libexecinfo)?

**Comment by ghost** [comment]
I don't think the issue is specifically musl, just that the Odamex CMake system is not checking for the existence of the execinfo header and library files before trying to build -- currently it's just assuming it is installed without checking (execinfo is provided by glibc so that's why it happens to work in that case).

The solution for this issue is just to explicitly check for execinfo in the CMakeFiles before proceeding to build. That should work regardless of whether the system has execinfo provided by glibc or independently by libexecinfo.

**Comment by leximayfield** [comment]
I'm aware.  I was asking if you could check to see if using libexecinfo actually fixed the problem, or if it resulted in a different error.

**Comment by ghost** [comment]
Oh sorry, I see what you mean. I decided to test this on Alpine Linux. I installed the `libexecinfo` and `libexecinfo-dev` packages using the apk package manager. Although this provided the missing `execinfo.h` and I was able to continue, I ended up hitting a new error about an undefined reference to `backtrace`. I suspect libexecinfo is not completely compatible with glibc execinfo.

Perhaps an alternative solution would be to make this functionality optional in Odamex, then users without these functions can disable it before building.

**Comment by ghost** [comment]
I'm sorry, I forgot to link the library so that's why I was getting the undefined reference error message. After providing the `-lexecinfo` switch to the compiler, the build completes without error and I'm able to launch the Odamex client as expected. Still, it would be nice to make this feature optional rather than required by Odamex.
