### ISSUE TITLE
[BUG] ANIMDEFS parser error causes wad not to load

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#547]
**Describe the bug**
![image](https://user-images.githubusercontent.com/22926877/153655480-f4aa8413-c416-4592-9c30-ce449de97136.png)

**Build that the bug occurred in**
Odamex 10

**To Reproduce**
Load d4v.wad

**Screenshots, NetDemos, & Crash Dumps**
Wad is here: (https://www.dropbox.com/s/hnrwo7z7rgka5hp/D4V_v3.2.1.zip?dl=1)

**Comment by DeathEgg** [comment]
This particular bug is caused because the parser isn't paying attention to the case sensitivity of the tokens, but it can't be fully parsed anyway because Odamex only currently supports Hexen's ANIMDEFS format and not ZDoom's extensions. I'm going to look into this to see what I can do.

**Comment by rakohus** [comment]
Fixed in #561
