### ISSUE TITLE
[BUG] If Automap uses custom colors, client crashes

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#554]
**Describe the bug**
If custom automap colors are enabled, 

**Build that the bug occurred in**
Odamex 10

**To Reproduce**
Turn on Odamex Custom Automap, Open automap

**Expected behavior**
Don't crash

**Screenshots, NetDemos, & Crash Dumps**
Crash dump

[odamex_g5880b_22724_20220214T085339.zip](https://github.com/odamex/odamex/files/8059268/odamex_g5880b_22724_20220214T085339.zip)

**Comment by Acts19quiz** [comment]
I would like to add that turning on the automap overlay also causes a crash as soon as one tries to open the automap.

**Comment by rakohus** [comment]
Confirmed both issues listed are fixed in PR #590.
