### ISSUE TITLE
[BUG] Setting Ping Quality values manually doesn't work for orange and red

### ISSUE THREAD

**Issue by nikovaan** [odamex/odamex#556]
**Describe the bug**
In Odamex Launcher settings, if I try to set a value for orange or red Ping Quality using keyboard, it discards the value and puts in 997 for orange and 999 for red.

**Build that the bug occurred in**
The Odamex Launcher version 10.0.0 - Protocol Version 8

**To Reproduce**
Highlight the value for orange/red ping quality, input a new one with keyboard.

**Expected behavior**
Same as green ping quality: it accepts the value as long as it is within sanity bounds. (between green and red for orange, higher than orange for red)

**Screenshots, NetDemos, & Crash Dumps**
orange: https://puu.sh/IJj9E/ce657b50ae.png -> https://puu.sh/IJj9L/f02c2cde0d.png -> https://puu.sh/IJj9W/e233ddb13c.png
red: https://puu.sh/IJjac/0f5da8a22f.png -> https://puu.sh/IJjaq/b08c2f3d42.png -> https://puu.sh/IJjaG/0912ecd040.png

**Additional context**
Windows 10 Education N version 20H2. English (Finland) Format, Japanese system locale, Finnish keyboard layout.
Freshly downloaded  and extracted odamex 10.0.0 64 bit zip (not installer), one wad dir was input to odamex configs.
Odamex was set up in F:\ drive in a new folder specifically for it.

**Comment by drivingspectrum** [comment]
[odalaunch_pqspinctrl_fix.zip](https://github.com/odamex/odamex/files/8069485/odalaunch_pqspinctrl_fix.zip)

This patch should resolve it

**Comment by rakohus** [comment]
@drivingspectrum could you please submit this patch as a PR?

**Comment by rakohus** [comment]
@drivingspectrum patch applied and will be available in 10.1 release.
