### ISSUE TITLE
[FEATURE] Setting for how long chat messages are shown

### ISSUE THREAD

**Issue by weatherman115** [odamex/odamex#558]
**Is your feature request related to a problem? Please describe.**
Reading longer chat messages within ~3 seconds of getting them can be hard to do, especially if you're focused on gameplay.

**Describe the solution you'd like to see**
In-game setting for how long a chat message can stay on screen.

**Describe alternatives you've considered**
Additional option for how many lines of messages can be shown at once
Ability to scroll through previous chat messages

**Additional context**
Happened a lot during the Horde event.

**Comment by rakohus** [comment]
This was addressed by AlexMax in #692, merged into stable, and will be in 10.2. Thank you for the request @weatherman115.
