### ISSUE TITLE
[FEATURE] Interpolate Various Aspects of Client POV

### ISSUE THREAD

**Issue by mmiovv2** [odamex/odamex#564]
**Is your feature request related to a problem? Please describe.**
The way that weapons bop isn't exactly the smoothest

**Describe the solution you'd like to see**
Smoother bopping animations

**Comment by bcahue** [comment]
I think this ticket should be converted to include everything else that needs to be interpolated in the player view. These include (as far as I know):

Scrolling Textures
Scrolling Flats
Weapon Bob
Automap rotation
Chasecam

Sector heights and player camera are already interpolated. These are what is noticeable as being "choppy" in uncapped framerates.

**Comment by rakohus** [comment]
> I think this ticket should be converted to include everything else that needs to be interpolated in the player view. These include (as far as I know):
> 
> Scrolling Textures Warped Textures Weapon Bob
> 
> Sector heights and player camera are already interpolated. These are what is noticeable as being "choppy" in uncapped framerates.

done

**Comment by rakohus** [comment]
Views when the player crosses through silent teleporters and certain deep water sectors also require interp. Their issue is more extreme however, quickly flashing a camera view at what I believe is 0,0 before returning to their correct position.

**Comment by rakohus** [comment]
Copying #573 into here and marking that as a duplicate. Content of request pasted below:

> **Is your feature request related to a problem? Please describe.** The way that the Automap currently rotates isn't exactly the smoothest.
> 
> **Describe the solution you'd like to see** Smoother Automap.

**Comment by bcahue** [comment]
> Views when the player crosses through silent teleporters and certain deep water sectors also require interp. Their issue is more extreme however, quickly flashing a camera view at what I believe is 0,0 before returning to their correct position.

What I believe is happening here is the client correctly assigns x/y/z to prevx/y/z on teleport but it's being overridden on the next rendering tic to run, causing the calculation to provide a bad result and sending the player camera out of map momentarily until the next gametic is experienced, fixing the camera.

**Comment by rakohus** [comment]
[odasilenttest.zip](https://github.com/user-attachments/files/16323294/odasilenttest.zip)

Wad for testing
