### ISSUE TITLE
[BUG] Wad won't load because "lump name is too long"

### ISSUE THREAD

**Issue by mmiovv2** [odamex/odamex#565]
**Describe the bug**
Trying to load a certain wad results in Odamex crashing with a zmapinfo message stating that "Lump name is too long" 

**Build that the bug occurred in**
10.0

**To Reproduce**
Load this wad in Odamex : https://www.mediafire.com/file/ng9rgx5l77wkofs/AD_MORTEMv4.zip/file

**Screenshots, NetDemos, & Crash Dumps**
(https://imgur.com/a/Ey704aJ)

**Comment by rakohus** [comment]
Confirmed in latest stable. This is a parsing error on `ZMAPINFO` lumps. @DeathEgg do you know if any of your new mapinfo changes might resolve this?

**Comment by rakohus** [comment]
Resolved as part of #600. Thanks @mmiovv2  for the report and @DeathEgg for the fix.
