### ISSUE TITLE
[BUG] Netdemo doesn't playback. "Error: Unknown object code (0) in archive"

### ISSUE THREAD

**Issue by Ru5tK1ng** [odamex/odamex#567]
**Describe the bug**
When trying to play some demos, the error message below occurs:

'Error: Unknown object code (0) in archive
Demo has ended.'

**Build that the bug occurred in**
Odamex 10.0.0 (g5880b-8048)

**To Reproduce**
Play back this demo:

https://www.sendspace.com/file/yox5ys

**Expected behavior**
You shouldn't be able to play it.

**Additional context**
Player who made the demo appears to be able to play it back without issue.

**Comment by bcahue** [comment]
I believe this was a demo created in an old version of Protobreak. Can you confirm if this was D'Sparil's demo recorded on commit c2aed5?

**Comment by Ru5tK1ng** [comment]
After running -version on his client, he was revealed to have been running protobreak, GC2AED-1.

**Comment by rakohus** [comment]
User was on an old experimental version of the client so not entirely a "bug". It raises the cause for a new function that alerts the player if they're on a non-stable/release branch, but it calls for a new feature request to be opened.
