### ISSUE TITLE
[FEATURE] Showing item count in Automap

### ISSUE THREAD

**Issue by mmiovv2** [odamex/odamex#570]
**Is your feature request related to a problem? Please describe.**
I've been using Odamex for singleplayer recently and I'm missing being able to tell how many items I have left to collect, a feature present in other sourceports.

**Describe the solution you'd like to see**
Add an option to allow for Automap to show the item count on a map.

**Comment by rakohus** [comment]
Added to stable for 10.2 release in #719. Thanks @bcahue
