### ISSUE TITLE
[BUG] Getting "SZ_GetSpace: overflow"  in a single player campaign

### ISSUE THREAD

**Issue by mmiovv2** [odamex/odamex#572]
**Describe the bug**
Getting a weird bug exclusive to Odamex while playing AD MORTEM where an imp's position get's misplaced resulting in the message ; "[BUG] Getting "SZ_GetSpace: overflow".

**Build that the bug occurred in**
10.0

**To Reproduce**
No idea, it just happened.

**Expected behavior**
As far as I know, bugs like these shouldn't occur in single play.

**Comment by rakohus** [comment]
Confirmed fixed in [b52ff95](https://github.com/odamex/odamex/commit/b52ff95b2b61504109a99da61f51f1036d7b0c68). Thanks @AlexMax
