### ISSUE TITLE
[FEATURE] Taunt

### ISSUE THREAD

**Issue by mmiovv2** [odamex/odamex#574]
**Is your feature request related to a problem? Please describe.**
Some sourceports have the ability to "taunt" using a key resulting in a certain sound effect playing

**Describe the solution you'd like to see**
Add the ability to taunt.

**Comment by rakohus** [comment]
Outside of the scope of features we're looking to provide at this time. Thank you for the request though.

**Comment by mmiovv2** [comment]
No problem.
