### ISSUE TITLE
[BUG] Instance of Spectator Causing a Change in Map (client-side only?)

### ISSUE THREAD

**Issue by Hekksy** [odamex/odamex#576]
**Describe the bug**
A spectator is causing a sound effect to play in a map. 

**Build that the bug occurred in**
Odamex 10.0.0 G5880B

**To Reproduce**
In Ad Mortem map03, if you walk into the exit area as a spectator, you will start to hear the slow floor lower sound effect, even though you are a spectator. The map does not appear to change at all, so I presume this noise is playing client-side only.

**Expected behavior**
This is unintended behavior because spectators should have no impact on the state of the map even if client-side only.

**Screenshots, NetDemos, & Crash Dumps**
https://streamable.com/8ugrlt
[Odamex_BUG576_AD_MORTEM.WAD_MAP03.zip](https://github.com/odamex/odamex/files/8111837/Odamex_BUG576_AD_MORTEM.WAD_MAP03.zip)

**Additional context**
AD_MORTEM.WAD

**Comment by rakohus** [comment]
Confirmed fixed via #568.
