### ISSUE TITLE
[BUG] Line Types Related To Raising and Lowering Ceiling Not Working

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#578]
**Describe the bug**
Linedef types 40, 41, 69, 193, 194, 198, 199 and 201 (and possibly others, these are just the ones I've tried so far) all either have no effect besides playing a sound, or lower the ceiling to a height of 0.

**Build that the bug occurred in**
Odamex 10.0.0

**To Reproduce**
Try activating any of these linedef types and the tagged sector(s) will have the behavior described.

**Expected behavior**
The ceiling should raise/lower by the amount specified.

**Additional context**
This was in a Hexen format map.

**Comment by rakohus** [comment]
Tested and confirmed fixed via #568. Thanks @bcahue!
