### ISSUE TITLE
[BUG] Crash when spawning custom enemy in horde

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#580]
**Describe the bug**
I tried recreating the pyro knight from Valiant. It works as expected if placed in a level, but whenever it gets spawned in horde mode the game instantly crashes.

**Build that the bug occurred in**
Odamex 10.0.0

**To Reproduce**
hordewave fire and brimstone
[first_horde_attempt.zip](https://github.com/odamex/odamex/files/8129577/first_horde_attempt.zip)

**Expected behavior**
The game not to crash

**Screenshots, NetDemos, & Crash Dumps**
[crash_dump.zip](https://github.com/odamex/odamex/files/8129572/crash_dump.zip)

**Additional context**
I'm new to this so there's still a possibility of user error somewhere.

**Comment by bcahue** [comment]
This was solved by using the correct Deh_Actor_158 in HORDEDEF, but I will leave this open as it shouldn't crash when you use an undefined dehacked monster, and instead should error before start to prompt the author.
