### ISSUE TITLE
[BUG] Hexen Format sector action 1024 no longer triggers secrets

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#586]
**Describe the bug**
Hexen Format sector action 1024 (found through "Generalized Effects" in map editors like Doom Builder/2) no longer triggers secrets, including HUD messages (if enabled) and "Secrets Found" in Intermission Screen tallies. This is a regression from 0.9.5. Other generic sector actions like damage still seem to work. Sector action 8 for Doom Format maps still works.

**Build that the bug occurred in**
v10.0.0 g5880b-8048

**To Reproduce**
Walk through any sector with action 1024 in a Hexen format map.

**Expected behavior**
Hexen sector action 1024 should trigger secret alerts and count towards "Secrets Found" in the Intermission.

**Screenshots, NetDemos, & Crash Dumps**
An attachment with map MAP01 is included.
[SECRETS.zip](https://github.com/odamex/odamex/files/8145416/SECRETS.zip)

**Comment by rakohus** [comment]
Hi @Acts19quiz, will look into this. We abstracted our map formats in Odamex 10 so there are maybe some small bugs like this still kicking around. Will evaluate soon. The zip seems empty.

**Comment by Acts19quiz** [comment]
My bad. I updated the first post.

**Comment by rakohus** [comment]
Fixed in #587. Thanks for the report @Acts19quiz
