### ISSUE TITLE
[BUG] Unanimated warped flats in ANIMDEFS prevent Odamex from running

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#588]
**Describe the bug**
Definitions for warping static flats in an ANIMDEFS lumps (i.e. "WARP flat TWISTED") cause Odamex to abort upon trying to start. Specifically, with the error, "Script Error: ANIMDEFS:#: Animation needs at least 2 frames". This is a regression from Odamex 0.9.5.

**Build that the bug occurred in**
v10.0.0 g5880b-8048

**To Reproduce**
Load any WAD with ANIMDEFS and a flat definition for warping that flat.

**Expected behavior**
Odamex should start, load the WADs, and warp the flat indicated in ANIMDEFS.

**Screenshots, NetDemos, & Crash Dumps**
[A WAD with MAP01 is provided for testing.](https://github.com/odamex/odamex/files/8145634/WARPED.zip)

**Additional context**
WARP definitions (and the sample WAD) work identically in Odamex 0.9.5, ZDaemon, ZDoom, and GZDoom. It's only Odamex 10.0.0 where things break down. This seems like it could bust a number of heretofore-compatible WADs.

**Comment by rakohus** [comment]
Thank you. Is an issue from parsing changes going into Odamex 10. @DeathEgg may have some awareness of what is happening here.

**Comment by DeathEgg** [comment]
This is due to the fact that ANIMDEFS is currently only supported in its original Hexen form, not with ZDoom additions. There's currently a pull request that prevents the game from crashing on load, and eventually (once the new resource file system is implemented) I plan on going through and implementing the ZDoom features.

**Comment by rakohus** [comment]
Fixed by @DeathEgg in [52c9483](https://github.com/odamex/odamex/commit/52c948346413f8165e2be700cf755003a7b998fa). Will be in next release. Thanks for the report @Acts19quiz.

**Comment by Acts19quiz** [comment]
No problem, and you're welcome.
