### ISSUE TITLE
[BUG] Custom map names (non- E#M# or MAP##) do not display their level titles in the automap or console

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#592]
**Describe the bug**
Map names that do not follow the E#M# or MAP## convention (e.g., ODX##, LOL##, D2DM#) do not display their level titles in the automap or console even when supplied with a correct MAPINFO. They display correctly in the Intermission Screen. This is a regression from Odamex 0.8.3 to 0.9.#.

**Build that the bug occurred in**
v0.9.1 g095f2-6776
...
v10.0.0 g5880b-8048

**To Reproduce**
Make a custom map with a map name other than E#M# or MAP##, and give it a full definition (including level title) in a MAPINFO lump. Turn on the automap or view the console while playing that level.

**Expected behavior**
The level title in MAPINFO should display in the automap and console like it does in the Intermission Screen.

**Screenshots, NetDemos, & Crash Dumps**
[This test map is mapped to ODX01.](https://github.com/odamex/odamex/files/8149274/MapNameTest.zip)

**Additional context**
The bug happens whether using "map ODX01 "Custom Title"" or "map ODX01 lookup HUSTR_****". It also happens whether using old MAPINFO formatting or newer formatting (using brackets and equals). Odamex 0.9.0 outright refuses to start when presented with such a map, so 0.9.1 is the true start of the bug as presented. Odamex 0.8.3 works perfectly with such maps, identically to ZDaemon, ZDoom and GZDoom, which is why I don't think this is an absent feature.

**Comment by rakohus** [comment]
Did a little bit of research. The map began to load again after @AlexMax's commit in [3ec91ab](https://github.com/odamex/odamex/commit/3ec91ab5ccbb59d1781e5b5ee8dcf2306e50c3ff), "Trim level name", in the `deh-strings-fix` branch. As you note, the map name is incorrect everywhere but the intermission screen.

Unfortunately, all the test artifacts from before October 2020 are expired on Github as well. The change in behavior occurs somewhere between May 2020 and October 2020.

**Comment by rakohus** [comment]
Resolved as part of #600. Thanks @Acts19quiz for the report and @DeathEgg for the fix.
