### ISSUE TITLE
[BUG] "Always Freelook" in "Mouse Setup" doesn't acknowledge ON status when launched with -warp.

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#601]
**Describe the bug**
When loading from command line ("odamex -iwad ****.wad -warp ##") or ZDL with a map specified, Odamex will not acknowledge that "ALWAYS FREELOOK" is set to "ON" until either a new game is started, the "map" console command is used to warp to a different map, or "idclev/leesnyder" is used. Beating the level you start on by command will not clear the issue. This is a regression from Odamex 0.9.5.

**Build that the bug occurred in**
v10.0.0 g5880b-8048

**To Reproduce**
Launch Odamex form command line, ZDL, or any other similar utility that forces Odamex to start from a specified map (and not just the title screen). Go into OPTIONS, MOUSE OPTIONS, and either set ALWAYS FREELOOK to ON or have it ON already upon starting the map. Either way, ON status won't be acknowledged until starting a new game.

**Expected behavior**
Exempting netgames with freelook disabled, the option to turn mouse freelook on should be instantaneous and not dependent on starting a new game.

**Additional context**
This doesn't seem to affect going into a server, assuming the server has sv_freelook set to 1. Whether going into such a match with Freelook ON, or setting it ON in the middle of a game, it will be accepted. This seems to be specific to single-player. Players settings get semi-forgotten every time they try to fast-start Odamex.

**Comment by rakohus** [comment]
Just want to chime in and say how annoying this bug is when testing a map straight out of UDB, which uses `-warp`

**Comment by rakohus** [comment]
I regression tested this. Pretty sure it came in with the horde branch in the following commit: [1dd6e34](https://github.com/odamex/odamex/commit/1dd6e340bac957653fcea239a8bbc4f371e5ace9)

**Comment by rakohus** [comment]
Seems to have been resolved in [17493e6](https://github.com/odamex/odamex/commit/17493e6cdd6e1c1d95b14a265cf81c08b39cfcfe). Will close after it's merged into `stable`.

**Comment by rakohus** [comment]
Fixed and merged to stable in [a4e6967](https://github.com/odamex/odamex/commit/a4e69670322b8c1c7a991917c1842f01a9cc3eac). Will be fixed in 10.1 release. Thanks for reporting @Acts19quiz
