### ISSUE TITLE
[BUG] IWAD Selector: Make Chex Quest also load chex.deh

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#616]
**Describe the bug**
Not a bug, per se, but not really a feature either. Odamex should attempt to load chex.deh with chex.wad when using the iwad selector.

**Build that the bug occurred in**
Odamex 10

**To Reproduce**
![image](https://user-images.githubusercontent.com/22926877/157479296-41b70124-125d-4122-a3f3-849ea58fb314.png)

**Comment by bcahue** [comment]
Completed and merged to `stable`:

![image](https://github.com/user-attachments/assets/f14599ca-919d-4e91-8148-a708823edd48)
