### ISSUE TITLE
[BUG] Boom generalized ceiling movers, sector flat texture changed to wrong target

### ISSUE THREAD

**Issue by simc2** [odamex/odamex#624]
**Describe the bug**
If a Boom generalized ceiling mover should also change the sector flat Odamex changes the ceiling to have the target sector's floor texture. This happens in both the trigger and numeric models.

**Build that the bug occurred in**
Odamex 10.0.0 win32, tested in single player only

**To Reproduce**
(Trigger action lines.)

**Expected behavior**
The ceiling texture should change to match the target sector's ceiling texture.

**Screenshots, NetDemos, & Crash Dumps**
none.

**Additional context**
Test map for Doom2, map01. Hit the switches. Trigger model on the left, numeric on the right.
[changeCeilTexture.zip](https://github.com/odamex/odamex/files/8309355/changeCeilTexture.zip)

**Comment by rakohus** [comment]
Confirmed. Thank you for the test wad! Comparison of dsda v Odamex:

DSDA:
![image](https://user-images.githubusercontent.com/22926877/159148574-f9768ef7-b913-4eed-972b-bd266911101f.png)

Odamex:
![image](https://user-images.githubusercontent.com/22926877/159148587-8ccfeca9-049f-4b0f-95dd-03ec1d4911bd.png)

**Comment by bcahue** [comment]
Fixed. Thank you for making this bug extremely easy to fix by including a test wad! 
![Odamex_SOLO_20220320_223317](https://user-images.githubusercontent.com/2531014/159198462-b8f8ac26-74bf-4afc-9abb-791233b3a6f1.png)

**Comment by rakohus** [comment]
Confirmed. Thanks @simc2 and @bcahue
