### ISSUE TITLE
[FEATURE] Flash task on OS when a minimized player should be aware of an in-game event

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#637]
**Is your feature request related to a problem? Please describe.**
Players often minimize the game window during periods where their play is suspended. Examples include, but are not limited to, being dead in a survival mode and waiting for their next attempt, waiting for a competitive game to start, etc. I have observed this player behavior in both Horde and CTF modes recently.

**Describe the solution you'd like to see**
Flash the taskbar under the following conditions:

1. The Odamex client window is not in focus (minimized); AND
2. When ANY of the following game events occur:
a. The player is spawned in-game and a `restart` is passed by the server;
b. The player is spawned in-game and the pre-game countdown begins;
c. The player is brought back to life during any survival mode;

**Describe alternatives you've considered**
We have tinkered with some sound cues before i.e. Horde respawn sound. However, in the midst of a lot of action or background noise, it is not always noticable. Some OS, which support [SDL_FlashWindow](https://wiki.libsdl.org/SDL_FlashWindow) may not play in-game sounds while the window is not focused as well. 

**Additional context**
[SDL_FlashWindow](https://wiki.libsdl.org/SDL_FlashWindow) was implemented in SDL 2.0.16. The function seems pretty simple. May want to be careful of error handling when a negative error code is returned as we don't want Odamex client bombing out over this feature.

**Comment by bcahue** [comment]
Was fixed in #790
