### ISSUE TITLE
[BUG] Some Horde Mode Maps Give Super shotgun instead of Plasma Rifle

### ISSUE THREAD

**Issue by LagMaster218** [odamex/odamex#644]
For some reasons on maps when you collect crates, it will sometimes say "You got the plasma rifle" and then it gives you the supershotgun

Odamex Version : 10.0.0.0.0.0.0

Haven't captured a screenshot due to the fast paced horde mode

**Comment by rakohus** [comment]
thanks @LagMaster218. We'll need some evidence to go on. You can go into the Odamex networking menu and set Odamex to always record a netdemo. If you are able to capture this issue, we can act on it. Absent another report or further information, this bug may be closed.

**Comment by rakohus** [comment]
Alert behavior changed in 10.1, so I'm going to wipe this bug out for now. Feel free to re-open if you observe it and can post a demo, screenshot, etc.

**Comment by LagMaster218** [comment]
Alright cool, Ive been trying to find it so I can submit another report!
