### ISSUE TITLE
[BUG] Hard crash after taking very high melee damage

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#650]
**Describe the bug**
Died from A_MonsterMeleeAttack, immediate hard crash.

**Build that the bug occurred in**
Release 10.1 ([0e9d3b5](https://github.com/odamex/odamex/commit/0e9d3b5783d043ac36d069bf45c51f22519ca171)

**To Reproduce**
Run latest dev odahorde wad

**Expected behavior**
Not crash

**Screenshots, NetDemos, & Crash Dumps**
Dump:
[odamex_g0e9d_20576_20220409T041914.zip](https://github.com/odamex/odamex/files/8456235/odamex_g0e9d_20576_20220409T041914.zip)

**Comment by bcahue** [comment]
This dump has 0 bytes, also a WAD would be easier to troubleshoot for me.

**Comment by bcahue** [comment]
Hmm, got the wad that was causing it but couldn't get Odamex to crash after about 50 deaths with the monsters in question.

**Comment by rakohus** [comment]
I can't reproduce anymore. Not sure what's up. Will reopen if it starts happening again.
