### ISSUE TITLE
[BUG] Non-secret sectors are reported as secrets and insta-kill the player

### ISSUE THREAD

**Issue by dan5sch** [odamex/odamex#662]
**Describe the bug**
In certain WADs, specific sectors will produce one or both of two behaviors depending on the build settings:

1. The sectors, which aren't secrets, will periodically produce the "A secret is revealed!" message. Walking back and forth will sometimes cause the message to be shown repeatedly, incrementing the secrets counter on the map screen past the number of actual secrets.
2. The same sectors will occasionally insta-kill the player, playing the exploded-body sound effect.

**Build that the bug occurred in**
Odamex v10.1.0 (Stable, G5BE2-8307) compiled from commit 5be225f3bb6aad88d96c965c136145c75e067893 (HEAD at time of writing) on Ubuntu 20.04 using:

- `$ cmake ..` (bugs 1 and 2)
- `$ cmake .. -DCMAKE_BUILD_TYPE=Release` (bugs 1 and 2)
- `$ export CC=/usr/bin/clang; export CXX=/usr/bin/clang++; cmake ..` (**only** bug 1)
- `$ export CC=/usr/bin/clang; export CXX=/usr/bin/clang++; cmake .. -DCMAKE_BUILD_TYPE=Release` (bugs 1 and 2)

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
clang version 10.0.0-4ubuntu1
cmake version 3.16.3

**To Reproduce**
1. Build as described above
2. Run $ odamex -iwad DOOM2.WAD -file ICARUS.WAD
3. Start a new game on MAP01 (difficulty: ITYTD and HNTR both produced issue), and get the blue key for access to the chapel area
4. Save the game before entering the blue key door
5. Enter the room, walk onto the wooden chair, and kill the imps that appear
6. Walk around the center area of the room, near the stairs and the green floor design

**Expected behavior**
No secret is reported, and the player does not go splat.

**Screenshots, NetDemos, & Crash Dumps**
[odamex_secret_insta_kill.zip](https://github.com/odamex/odamex/files/8598251/odamex_secret_insta_kill.zip)

**Additional context**

- Tested in single player with all compatibility options set to the default "OFF"
- In testing, it can take anywhere from a few seconds to 30 seconds for the death bug to trigger while walking around the room
- The "A secret is revealed!" message may appear several times before the player dies, as often as every few seconds
- The issue will occur consistently after reloading a save before the affected area
- I've observed the same bugs together in other maps (e.g., TNTR.wad MAP32). In every case, the bugs occur in a consistent location in the map.
- As visible in one of the screenshots, I also saw hall-of-mirrors artifacts on the grey stairs in the Icarus room; these did not appear in Crispy Doom when I tested the same room there.

**Comment by rakohus** [comment]
Tested and confirmed behavior following the instructions. The compatibility physics flags don't affect the bug. Took about 2 minutes for it to occur.

**Comment by dan5sch** [comment]
I found another circumstance where the "A secret is revealed!" message can occur repeatedly:

Steps to reproduce:

1. Start playing any level with a secret (e.g., Doom 2 MAP01)
2. Enter a secret sector, triggering the message (e.g., the secret in the room to the left in the hallway)
3. Save the game
4. Load the save
5. Enter the secret sector again

Expected behavior:

Nothing happens

Actual behavior:

"A secret is revealed!" appears again, and the map-screen secret count increases by one. Repeat steps 3 to 5 to keep increasing the count. The message only appears once per reload.

**Comment by rakohus** [comment]
Thank you for the report @dan5sch. After testing, it looks like @bcahue's PR #663 has resolved both bugs you mentioned. Thanks to everyone involved.
