### ISSUE TITLE
[BUG] Turning on "WIDESCREEN" improperly scales the position of Intermission graphics.

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#669]
**Describe the bug**
Turning on "WIDESCREEN" (OPTIONS>SET VIDEO MODE) improperly scales the position of Intermission graphics, specifically WISPLAT and WIURH#. They will move from their intended original positions outward towards the left and right edges based on their proximity to the center. Close to the center, they will barely move. The more outward left or right the graphics, the farther they will move. The splotches will not be near the buildings and landmarks representing their respective levels. In the worst cases, they will bleed past the edges of the episode background map graphic into the black boarders.

**Build that the bug occurred in**
v0.9.2 (ge0d79-6829)
...
v10.1.0 (g0a84-8300)

**To Reproduce**
Turn on WIDESCREEN on any of Registered/Ultimate DOOM's first three episode. You can do it before hitting the exit, or even during the Intermission itself. Any WISPLAT or WIURH# graphics will readjust position.

**Expected behavior**
Intermission graphics (WISPLAT and WIURH#) should keep their positions on the WIMAP# graphics, not adjust on a ratio relative to the screen ratio and distance from the center.

**Screenshots, NetDemos, & Crash Dumps**
[Screenshots with Widescreen enabled and disabled (resolutions are different, but this has no impact on the result).](https://github.com/odamex/odamex/files/8721696/Widescreen_Intermission_screencaps.zip)

**Additional context**
Screen resolution seems to have no bearing. The issue seems specific to whether "WIDESCREEN" is enabled or not. The map animations also don't seem to be affected.

**Comment by bcahue** [comment]
Fixed as part of the fixes packaged with #983
