### ISSUE TITLE
[BUG] HUD issues in custom duel mode

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#676]
**Describe the bug**
Wasn't sure whether to file this under bug or feature. Feels like a bug to players, technically a feature. Tagged as both. A few HUD/scoreboard issues in the custom "match duel" mode. 

**Build that the bug occurred in**
10.1

**To Reproduce**
Set the following settings in duel:
`g_rounds 1`
`g_roundlimit 3`
`g_winlimit 2`

**Expected behavior**

- Scoreboard sorts players by rounds won rather than total frags in that round. It's jarring.
- HUD spread widget shows the round spread rather than the frag spread. Would be a bonus if we can show round tally somewhere.

**Comment by rakohus** [comment]
Additionally, could show frags / wins on the scoreboard instead of frags / deaths

**Comment by rakohus** [comment]
@AlexMax the scoreboard part of the issue is corrected with your branch and works perfect. Passes the test. However, the HUD spread widget part of the issue remains unaddressed

**Comment by rakohus** [comment]
My last comment is addressed in Blair's #717 PR. The branch + 717 will fully resolve the issue once it's merged into stable.

**Comment by bcahue** [comment]
This due to be closed yet? I believe all necessary changes were made.
