### ISSUE TITLE
[BUG] Dummy sectors break when activated on different servers

### ISSUE THREAD

**Issue by thefatwilly** [odamex/odamex#686]
**Describe the bug**
Sunlust Map06 sectors 172, 282, 202, 281, 278 and 280 is supposed to rise when used with the yellow key utilizing dummy sectors and a voodoo doll to activate a "W1 Lift Raise to Next Highest Floor (fast)". Currently this has two behaviors in two different servers;

[NY] Funcrusher Sunlust Survival zds://104.236.194.168:10673/od - will completely ignore its dummy sectors and simply choose other sectors to reference for the lift to aim for. The lift becomes inaccessible entirely and cannot be fixed to progress.

[WDL] doomleague.org Sunlust Juggernaught Survival zds://74.91.112.85:10304/od with pk_smooth - on this server, the map executes the action without fail and only minor desyncs are present but the lift is still very much useable and is possible to reach the end of the map.

Singleplayer - I went through and tested this in singleplayer using both sets of cvars, including ones that don't even matter like sound, actor height, etc. I cannot get this to replicate in singleplayer with either sets of dmflags.

**Build that the bug occurred in**
10.1.0

**To Reproduce**
Simply join the servers.

**Expected behavior**
Lift to be accessible.

**Screenshots, NetDemos, & Crash Dumps**
Demos of both server playthroughs included.

**Additional context**
Alexmax let me run around on his Funcrusher server with cheats on, I noclipped around the map and the voodoo doll slides down the dummy sector just fine, but only the dummy sectors joined with the lift (that allow it to manipulate what height to be brought to) did not complete its actions fully. Noclipping inside the lift even shows that some of the floors actually closed up into the ceiling. The entire lift is supposed to rise like a Boom 'elevator'.
[WDL doomleague Sunlust Map07 Demo.zip](https://github.com/odamex/odamex/files/8995800/WDL.doomleague.Sunlust.Map07.Demo.zip)
[NY Funcrusher Sunlust Map07 Demo.zip](https://github.com/odamex/odamex/files/8995801/NY.Funcrusher.Sunlust.Map07.Demo.zip)

**Comment by rakohus** [comment]
Thank you for the detailed report. Fixed and committed in PR #687, will be in 10.2.0 release.
