### ISSUE TITLE
[FEATURE] Horde boss projectiles to mimic boss's palette status

### ISSUE THREAD

**Issue by thefatwilly** [odamex/odamex#697]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. Would just be nice to differentiate horde boss projectiles from standard projectiles, helps a player triangulate where a boss is if it cannot be seen right away. Also allows players to threat assess if they *must* take damage from a source then they can run into a normal enemy projectile than a suped up boss projectile.

**Describe the solution you'd like to see**
Boss projectiles to look like the palette swapped versions of their owners, to be gold, sparkling, etc.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by rakohus** [comment]
Added to stable for 10.2 release in #722. Thanks @bcahue
