### ISSUE TITLE
[CHANGE] Make `g_preroundtime` count down before rounds beyond 1

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#705]
**What is the existing behavior? Please describe.**
Currently, two variables exist called `g_preroundtime` and `g_postroundtime`. They are as they say. pre counts down to the start, post is the amount of time after the match before moving on. 

Currently, if `g_rounds > 1`, the game will sit on the post round timer and then _immediately_ jump into round 2 without notice. See attached video.

**What is the desired behavior? Why are you requesting the change?**
If `g_rounds > 1`, run `g_postroundtime` as it currently does, then count down to the next round with `g_preroundtime`.

This request is based on the attempt to implement the new "Match Duel", which is a best 2/3 round duel. Currently, the transition into the 2nd and 3rd rounds is unexpected and jarring to players. A countdown similar to what happens for the first round would be helpful and intuitive.

**Additional context**
Video of current behavior:

https://user-images.githubusercontent.com/22926877/179122791-10d96d4e-41d7-4819-92e4-0c7a3de4269f.mp4

**Comment by leximayfield** [comment]
The old logic, to my recollection, was on purpose.  I thought that people running around able to collect things before the game takes place didn't make sense, outside of a lives-based mode.  There, the preround allows you to get your bearings before all hell broke lose so you don't die in two seconds to spawn RNG like in Zandro.

However, recalling how Zandro does things, in the Duel gamemode of that port they actually spawn players in during the duel preround countdown, but then the moment FIGHT happens it resets the map again.  That gives you a heads-up to know that about to be playing.

Would having a cvar that forces a map reset on `PREROUND_COUNTDOWN` -> `INGAME` work for you?  And then we just enable preround on all FFA/TDM gamemodes?  And if you don't want preround, just set it to 0?

**Comment by leximayfield** [comment]
I committed a `preround-reset` branch that contains a `g_preroundreset` cvar.  If you set this to true, the map will reset as described.

Preround is also now enabled for all round-based DM/TDM gamemodes.  Though if I'm being honest, we could enable it for CTF too - but preround without reset doesn't make much sense to me (nothing stopping us though).

**Comment by rakohus** [comment]
Tested it in multiple modes and they all seem solid. Thank you for your work on this @AlexMax. Good to merge.

**Comment by rakohus** [comment]
Merged to stable from PR #714. Thank you
