### ISSUE TITLE
[FEATURE] Compat option to uncap Pain Elemental-spawned Lost Soul limit

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#707]
**Is your feature request related to a problem? Please describe.**
Ran into this often during Horde sessions, where the limit for Pain Elemental's Lost Souls on the map was very quickly reached, rendering Pain Elementals a non-threat and easily neutralized.

**Describe the solution you'd like to see**
While this behavior will definitely aid new and amateur players, and maintain compatibility for obvious reasons, I think the best implementation would be a compatibility var that toggles this limit on or off. Server administrators can then disable it for MAXIMUM LOST SOUL MAYHEM.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by rakohus** [comment]
Pushed to stable in #716. Thanks for the patch @electricbrass
