### ISSUE TITLE
[CHANGE] Horde monster spawners scrolling with sectors

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#708]
**What is the existing behavior? Please describe.**
Sector specials 201-224 in Hexen format will pull Horde Spawners in the direction indicated by the special.

**What is the desired behavior? Why are you requesting the change?**
To have the monsters spawned scroll with the sector, but not the spawner itself. This allows mappers fixed points on scrolling sectors to work with monster spawns in a predictable manner.

**If applicable, describe alternatives you've considered**
None.

**Additional context**
WAD attached showing behavior. Current behavior moves the spawner to the right side of the room. Requested behavior would keep the spawner placed as intended directly in front of the player, but monsters spawned would still be affected.
[horde-spawner-scroll.zip](https://github.com/odamex/odamex/files/9138502/horde-spawner-scroll.zip)

**Comment by rakohus** [comment]
Tested and confirmed #711 changes to the requested behavior. Thanks @AlexMax

**Comment by rakohus** [comment]
Resolved and merged in #711. Will be in 10.2. Thanks for the request and test wad.
