### ISSUE TITLE
[CHANGE] Horde monster spawners to be affected by -nomonsters

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#709]
**What is the existing behavior? Please describe.**
Mappers who wish to look at their Horde maps in-game, undisturbed by the Horde mechanics find that unlike normal placed monsters, spawners do not adhere to -nomonsters behavior, starting a Horde round.

**What is the desired behavior? Why are you requesting the change?**
Spawners to be inactive when no monsters are intended. This is a change pitched to ease mapper workflow.

**If applicable, describe alternatives you've considered**
None.

**Additional context**
It appears to be extra, unnecessary effort for creators to uncheck particular difficulties in their spawners or delete/move them to visually inspect their map for testing or screenshot purposes.

**Comment by rakohus** [comment]
Tested and confirming #710 addresses this issue. Thanks @AlexMax

**Comment by rakohus** [comment]
Resolved and merged in #710. Will be in 10.2.
