### ISSUE TITLE
[BUG] Doors/Lifts/Crushers instantly delete Horde-spawned things

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#715]
**Describe the bug**
It appears as though that anything that has the potential to restrict height lower than a Horde-spawned object's height will cause it to instantly disappear. You'll also notice that if it's a monster that gets deleted, the bar fills up.

**Build that the bug occurred in**
10.1 Release

**To Reproduce**
Run the attached map and press the switch you spawn up against when things spawn. You'll see this applies to powerups, caches and monsters. The map shows a door in action, but I was able to reproduce it with crushers and lifts.

**Expected behavior**
Probably **not** insta-delete monsters.

**Screenshots, NetDemos, & Crash Dumps**
Test WAD is attached.

**Additional context**
N/A
[horde-door.zip](https://github.com/odamex/odamex/files/9164718/horde-door.zip)

**Comment by rakohus** [comment]
Added to stable for 10.2 release in #721. Thanks @bcahue
