### ISSUE TITLE
Game randomly times out(not Internet related)

### ISSUE THREAD

**Issue by Saltmine2** [odamex/odamex#734]
**Describe the bug**
When I am playing Odamex online, at random moments during play my game will stop me in place as if my Internet has crashed. It will display the symbol near the top left corner of my game to show that I have lost connection to the server. However, my Internet is completely stable while this is happening, as I can still hear people talking and talk to others in Discord calls while my game is timing out. After watching back my demos, it says that I was disconnected from the server due to an "unrecoverable protocol error" but I have no clue what that means.

**Build that the bug occurred in**
Odamex v0.10.1 (g0a84-8300) 64-bit installation

**To Reproduce**
Just randomly playing the game online, I suppose.

**Expected behavior**
I would expect that I don't randomly time out during online games and that the game continues running smoothly.

**Screenshots, NetDemos, & Crash Dumps**
[Odamex_DUEL_20220803_110113_DUEL2020OA.WAD_MAP18.zip](https://github.com/odamex/odamex/files/9253130/Odamex_DUEL_20220803_110113_DUEL2020OA.WAD_MAP18.zip)
There are two demos in here of me dueling, I crash near the end both times.
![OdamexErrorConsoleSS](https://user-images.githubusercontent.com/110553585/182655787-352f45a9-2d89-47b2-85d8-490965f471f8.png)
This is a screenshot of the console at the end of one of the demos where I crash.

**Additional context**
I have tried reinstalling Odamex multiple times to no avail.

**Comment by leximayfield** [comment]
If it can't read a header, that's cause for concern, especially if everybody else on the server remains connected.

If you could, please post a demo.  I am actively working on retooling our netcode to be more reliable for bad connections.

**Comment by rakohus** [comment]
After following up with OP, unknown status. Please repost if the problem persists.
