### ISSUE TITLE
[FEATURE] If `cl_freelook = 0`, automatically center view

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#763]
**Is your feature request related to a problem? Please describe.**
Can't think of any practical reason someone wouldn't want the typical doom centered view if freelook is off. Currently, if you have mlook on and turn it off, you are stuck in the non-centered view unless you're aware of the `centerview` command (which maybe doesn't even work currently?)

**Describe the solution you'd like to see**
Get rid of the need for a `toggle "cl_freelook;centerview"` bind and reduce it to `toggle cl_freelook`

**Comment by leximayfield** [comment]
`centerview` _is_ being sent, but it does nothing.

I think that the better mouselook contributed semi-recently is stomping on it.

**Comment by electricbrass** [comment]
Typing `centerview` in the console doesn't seem to work, but if I bind it to a key it works fine. Lookspring works too. Yet all seems to be using the same bit of code.

Also commenting out the line in cl_game.cpp that sets `sendcenterview` to false results in it continuously centering my view after typing `centerview` or toggling `cl_mouselook`, as I would expect.

**Comment by electricbrass** [comment]
Binding a key to `toggle cl_mouselook` works correctly, centering the view. Anything that should center the view does not if the console or menu is open.

**Comment by bcahue** [comment]
This is fixed, if a little jarring because the `centerview` doesn't run until the console up/menu is off because it doesn't run ticks during that time.
