### ISSUE TITLE
"Server is full" Does Not Display

### ISSUE THREAD

**Issue by Hekksy** [odamex/odamex#765]
When you connect to a server that is full, it used to disconnect the client saying "Server is full." At some point this broke, and it says "cl_parsecommands: Could not decode message" and "Disconnected from server: unrecoverable protocol error" now

**Comment by leximayfield** [comment]
Please test #776 to see if it works for you.

**Comment by rakohus** [comment]
Tested #776 and confirmed the message now works. Thank you
