### ISSUE TITLE
[BUG] Decino Crash Dumps

### ISSUE THREAD

**Issue by Hekksy** [odamex/odamex#767]
**Describe the bug**
Crashes while attempting to connect to Decino's server with 64+ players

**Build that the bug occurred in**
10.2.0-g6c294-8435

**To Reproduce**
I connected to the server

**Expected behavior**
Don't crash when connecting

**Screenshots, NetDemos, & Crash Dumps**
Crash dump thread

**Additional context**
Special event server hosting various pwads and was full many times.
[Decino_crashdumps_10.2.zip](https://github.com/odamex/odamex/files/9438581/Decino_crashdumps_10.2.zip)

**Comment by leximayfield** [comment]
I believe #774 addresses this issue.

**Comment by rakohus** [comment]
I'm really not sure how to test this without having 64 players on a server, haha. Will just use these builds for a while and if nothing weird happens, we can close it

**Comment by rakohus** [comment]
Going to assume #774 fixed it as we haven't heard anything about this for a while
