### ISSUE TITLE
[BUG] Weapon numbers and stray red pixels on frag counter

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#773]
**Describe the bug**
In gamemodes with frags, the weapon numbers still show up, and it looks like there are some odd red pixels around the counter as well.

**Build that the bug occurred in**
10.2.0

**To Reproduce**
Pick up a weapon (besides the SSG) in deathmatch or any other mode with the frag counter.

**Expected behavior**
The weapon numbers shouldn't be there.

**Screenshots, NetDemos, & Crash Dumps**
![image](https://user-images.githubusercontent.com/84749759/188286122-fb8747a0-b8be-4a38-8d32-6220516da986.png)

**Comment by rakohus** [comment]
Tested and confirmed. Thank you for report @electricbrass and fix @AlexMax
