### ISSUE TITLE
[BUG] Boom Format Line Action 192 Does the Opposite

### ISSUE THREAD

**Issue by thefatwilly** [odamex/odamex#786]
**Describe the bug**
In boom the line special of 192 which is "SR Light Change to Brightest Adjacent" currently does the exact opposite of the action and turns the sector brightness down to an indeterminate amount.

**Build that the bug occurred in**
10.2.0 Stable currently offline unknown if possible in online

**Expected behavior**
For sector to become bright relative to an adjacent brighter sector

**Additional context**
Test Wad attached, careful as it has multiple testing related areas as well.
[testing wad.zip](https://github.com/odamex/odamex/files/9641797/testing.wad.zip)

**Comment by bcahue** [comment]
This can be closed I believe

**Comment by fuzztooth** [comment]
Fix merged with no additional feedback.  Closing.
