### ISSUE TITLE
[BUG] WAD changing-related crash

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#792]
**Describe the bug**
Another player and I were in the Monday Night Horde server. I died in Wave 1, and the other player died in Wave 2. But we made it to Wave 3, complete with resurrections. We briefly played that wave before (and I confirmed this later with the other player) the Odamex client crashed for both of us. When we rejoined (I was first), I found that not only had the map had also been changed, but also the WAD, from MAP43 of Hordamex to MAP11 of OdaHorde.

**Build that the bug occurred in**
10.2.0 (GF6615-8433)

**To Reproduce**
Although the crashes online occur sporadically with (as of yet) no known reproduction steps, the included netdemo of what happened live crashes at the exact same point at the end.

**Expected behavior**
Nothing in particular other than Odamex shouldn't (randomly) crash.

**Screenshots, NetDemos, & Crash Dumps**
[Here are netdemos of the map where the crash happened, and the following map.](https://github.com/odamex/odamex/files/9760005/Map_change_crash_000.zip) Note that the first netdemo has a slightly glitched intro, and that the timeline doesn't work. This wasn't part of the live gameplay. I think it's an unrelated issue due to my timing of when I cut the previous map's netdemo and when I started record. The first netdemo crashes just as Odamex did during live gameplay. The second netdemo probably contains nothing useful, but it's here anyway.

You will need hordamex-rc3.wad, odahorde_220530.wad and of course DOOM2.WAD.

[Here's the original crash dump.](https://github.com/odamex/odamex/files/9760008/odamex_gf6615_10020_20221004T202707.a19.zip) More crash dumps can be generated simply by viewing the first netdemo, but this is the original crash dump generated by live gameplay.

**Additional context**
It's unknown what caused this. Perhaps something is bad in MAP43 of Hordamex that caused a crash: We both crashed out, the player pawns on the server side were left hanging, died, thus forcing a map change. Or perhaps the server inexplicably changed maps (and WADs) in the middle of a match.

It should be noted the Monday Night server's on-the-fly WAD changing has occasionally produced other sporadic effects, like mass client disconnects. This may or may not be the cause here, or merely a byproduct.

**Comment by Acts19quiz** [comment]
_**Possibly**_ fixed as of 10.4.0. A test was performed around 3:30 AM EDT on the Monday Night Horde server. There were several WAD changes in a row in the map rotation without any issues. Players there included @rakohus, KDBlair, Manc, Xenaero, and myself.

**Comment by rakohus** [comment]
Should be fixed
