### ISSUE TITLE
[BUG] MAPINFO won't fall back to use Patch names for skys

### ISSUE THREAD

**Issue by bcahue** [odamex/odamex#809]
**Describe the bug**
For MAPINFO, listing a sky as "RSKY1" is valid as you can use patch names for skies. However, in Odamex, we throw an error of "Texture [sky lump name] not found" for MAPINFO sky1 sky2 and sky3 parameters that attempt to use patch names instead of texture names.

**Build that the bug occurred in**
Odamex 10.3.0 gb28e-1

**To Reproduce**
Load a wad with a MAPINFO lump that has a sky with a patch name such as 12 More Days of Christmas.wad (https://www.doomworld.com/idgames/themes/xmas/12moredays)

**Expected behavior**
For Odamex to get a sky via patch name if getting the sky via texture name does not work. Boom ports such as DSDA-Doom handle this.

**Screenshots, NetDemos, & Crash Dumps**
N/A

**Additional context**
While this *technically* isn't spec for Hexen's MAPINFO, Boom ports such as DSDA-Doom do support it.

**Comment by rakohus** [comment]
Solution was reached in bcahue's bevy of sky fixes
