### ISSUE TITLE
[BUG] MAPINFO enforces 8 char limit on all types of parameters in a 'next' token

### ISSUE THREAD

**Issue by bcahue** [odamex/odamex#810]
**Describe the bug**
Odamex will throw an error if it encounters a MAPINFO next token that isn't "EndSequence" and is higher than 8 characters. MAPINFO allows this to send players into an intermission after an EndSequence, and that intermission may have more than 8 characters.

**Build that the bug occurred in**
Odamex 10.3.0 gb28e-1

**To Reproduce**
Load a wad with a MAPINFO lump only that uses LANGUAGE lump string tokens, such as drlzoros.wad (https://www.doomworld.com/idgames/themes/xmas/drlzoros)

**Expected behavior**
Odamex to accept intermission tokens in a next token that's larger than 8 characters.

**Screenshots, NetDemos, & Crash Dumps**
N/A

**Additional context**
N/A

**Comment by electricbrass** [comment]
Adding on to this: It seems to only happen if loading as a command line argument or from the in-game console. Loading from the GUI does not throw this error.

**Comment by bcahue** [comment]
Fixed with #970
