### ISSUE TITLE
[FEATURE] Show items, kills, and secrets on HUD

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#814]
When playing in DSDA-doom it's very nice to have the option to keep the standard status bar while being able to see kills, items, and secrets without having to open the map to check. Something similar in Odamex would be nice to have for singleplayer and coop.

![image](https://user-images.githubusercontent.com/84749759/207114830-a482f981-be07-423a-a96d-6611d392b4fe.png)
(The extended hud in FDWL)

**Comment by rakohus** [comment]
That's a very popular thing to see during streams, so in my opinion, might as well rip it off wholesale. We have the font.
