### ISSUE TITLE
[CHANGE] Make sv_allowcheats usable offline (for Nightmare!/skill 4).

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#830]
**What is the existing behavior? Please describe.**
Odamex seems to have replaced the ZDoom standard of sv_cheats with its own sv_allowcheats. An interesting if minor distinction or change. The problem, though, is that as far as I've been able to tell, there's no way to enable cheat override offline. sv_cheats obviously doesn't do anything at all, and sv_allowcheats seems to work only online. If one wants (or needs) to be able to run cheats offline (like play testing things on Nightmare!/skill 4), there doesn't seem to be any way to currently do that.

**What is the desired behavior? Why are you requesting the change?**
Make sv_allowcheats work offline as well as online.

There are a number of reasons, either for play testing something on Nightmare!/skill 4 or even 'just for fun', that one might want to enable cheats, quick ammo drop, etc. on offline Nightmare!.

**If applicable, describe alternatives you've considered**
Adding in the classic ZDoom standard of sv_cheats.

**Additional context**
N/A

**Comment by rakohus** [comment]
Cheats seem to work fine offline, except in Nightmare skill. Is this request actually for allowing cheats in nightmare? If so, it seems like `sv_allowcheats` could just be expanded to if = 1, then allow cheats if `sv_skill = 5`. Am I misunderstanding this change request?

**Comment by Acts19quiz** [comment]
Correct, allow cheats in Nightmare offline. Cheats always work offline, but the reason on ZDoom you use sv_cheats offline (or its Odamex equivalent, sv_allowcheats) is for Nightmare!/skill 4. That's why I framed the issue not as not being able to use cheats offline, but not being able to use cheat block overrides offline (the primary reason for this is Nightmare!/skill 4).

The "alternatives I've considered" section is always my second or third option, an alternative to address the issue brought up--never my first or preferred option. I don't think two server variable is needed either, but well the tracker wants alternatives so there one is. d: (if sv_allowcheats is behaving as intended, add in another sv to accomplish what it does in ZDoom).

If this is actually possible offline (overriding cheat blocks, e..g Nightmare/skill 4), then yeah this is a misfire. I'm just not aware of how to do this.

**Comment by rakohus** [comment]
Tested #831 against issue and confirmed. `sv_allowcheats 1` now allows cheats in nightmare `sv_skill 5`. Closing. Thanks as always @Acts19quiz!
