### ISSUE TITLE
[BUG] When playing HacX, the player sprite (PLAY) in PLAYER SETUP clips past the gray Odamex box (M_PBOX).

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#839]
**Describe the bug**
When playing HacX, the player sprite (PLAY) in PLAYER SETUP clips past the top border of the gray Odamex box (M_PBOX).

**Build that the bug occurred in**
0.9.2 GE0D79-6829 (and probably older)
...
10.3.0 GB28EE-8578

**To Reproduce**
Go into PLAYER SETUP while playing HacX.

**Expected behavior**
The Player Setup sprite to stay within the bounds of Odamex's gray border box.

**Screenshots, NetDemos, & Crash Dumps**
![HacX_PSetup](https://user-images.githubusercontent.com/63941237/215233961-2250cffd-87ac-4665-bb22-60736812a860.png)

**Additional context**
Solutions considered:

- Change PLAYER SETUP such that, if HacX is the IWAD, drop the y-coordinate of the PLAY sprite so that it does not clip.
- Drop the y-coordinate of all games.
- Make a new bigger gray box (M_PBOX) sprite.
- Scale down the drawing of the PLAY sprite if HacX is the IWAD (not a fan of this one).
- Scale down the drawing of all PLAY sprites (also not a fan).

**Comment by rakohus** [comment]
Another potential solution: just render the player sprite in front of the box.

**Comment by Acts19quiz** [comment]
Maybe, but then my next Issue filed would be "HacX PLAY sprite displays past the box."

After reviewing the animation more carefully, I don't think my first two solutions will do the trick. There are seven pixels available to drop down, but the sprites go up 11 pixels past the red sandbox, through the gray box, and up to the main background itself.

**Comment by Acts19quiz** [comment]
So, I did expand M_PBOX 11 pixels in height and dropped PLAY by the same amount. However, expanding the height of the flame box (from 77 to 88) causes, well, this. I can expand the box from 77 to 83 before this starts. I could just split the difference, expand the fire box to 83, take M_PBOX down from 98 (new height) to 96, then drop PLAY by two or so. That should look pretty good.

The problem that just now occurred to me is if there are any mods out there specifically for Odamex that replace M_PBOX. That could be a compounding complication.
![M_PBOX_expand](https://user-images.githubusercontent.com/63941237/215349142-6b2a10c3-3824-4b78-96dc-e8a5d5a0fff0.png)
