### ISSUE TITLE
[BUG] `+RIP` flag doesn't work as intended

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#850]
**Describe the bug**
`+RIP` mbf21 flag doesn't work - projectiles blow up as normal on contact with actor.

**Build that the bug occurred in**
10.3

**To Reproduce**
Get hit with a +rip projectile.

**Expected behavior**
+RIP continues through the actors until it hits wall or an actor that is immune.

**Comment by bcahue** [comment]
Do you have a demo wad?

**Comment by rakohus** [comment]
[riptest.zip](https://github.com/odamex/odamex/files/11750313/riptest.zip)

Imp in the red lane with the red axe
