### ISSUE TITLE
[BUG] Generic obituaries confuses victim and killer.

### ISSUE THREAD

**Issue by rodylg** [odamex/odamex#875]
**Describe the bug**
Text obituaries sometimes display the message wrongly (potentially related to weapons modified via MBF21), confusing the victim and the killer. The kill feed feature displays the correct information.

**Build that the bug occurred in**
10.3.0

**To Reproduce**
Play any deathmatch game with VesperDM.

**Expected behavior**
As an example, obituary should read "Killer killed Victim." or "Victim was killed by Killer." instead of "Victim killed Killer."

**Screenshots, NetDemos, & Crash Dumps**
You can watch it in action on any of these NetDemo recordings:
https://youtube.com/playlist?list=PLZBU6VZrl63UPcdaMrv4cRSlI6ac7mljJ

**Additional context**
Might have to do with a localization string file mistake. It occurs in English but I'm not sure if this happens in other languages.

**Comment by Acts19quiz** [comment]
<https://github.com/odamex/odamex/issues/842> This may have already been addressed. I heard this mentioned a couple of times during Vesper testing. One of the devs can chime in to make sure. Assuming I'm reading this right, this is set to be fixed in 10.4.0.

**Comment by rakohus** [comment]
Thanks for the report @rodylg. It's addressed in 10.4 already. Look for 10.4.0 to release soon.

**Comment by rakohus** [comment]
Related to #784 and #842
