### ISSUE TITLE
[CHANGE] "Player became a spectator" message

### ISSUE THREAD

**Issue by rodylg** [odamex/odamex#881]
**What is the existing behavior? Please describe.**
The message on the hud says "Player became a spectator."

**What is the desired behavior? Why are you requesting the change?**
The message should read "Player became a spectator. (n frags, m deaths)". That will make advanced scorekeeping using demo replays easier.

**If applicable, describe alternatives you've considered**
N/A

**Additional context**
It should look similar to the topmost message
![Screenshot](https://github.com/odamex/odamex/assets/49259699/afda70b8-eb64-4388-8aec-59c0deeb3a4d)

**Comment by bcahue** [comment]
Thanks to @seanmleonard for the fix, this is now implemented in `stable`.
