### ISSUE TITLE
[BUG] MBF21 Seeking Projectiles Target Spectators

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#883]
**Describe the bug**
A MBF21 tracer projectile will seek spectators.

**Build that the bug occurred in**
10.3

**To Reproduce**
Use Vesper weapons 6/7 in a room where a spectator is.

**Expected behavior**
Not seek spectator actors.

**Comment by rodylg** [comment]
The mystery of the spooky ichor projectiles running in circles has been solved.
