### ISSUE TITLE
[BUG] `resource_files`: Loading pk3/zip crashes Odamex client/server

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#890]
**Describe the bug**
Loading pk3/zip crashes the client/server

**Build that the bug occurred in**
`resource_files` 65aabf2

**To Reproduce**
-file on dehacked.zip

**Expected behavior**
Doesn't crash. There may be a second bug underlying this. When attempting to load with just `-file` on the server, I received the following error:

```
=== ERROR: Unable to locate IWAD resource file.
GetLastError = 3 ===
```

Adding `-iwad doom2.wad` removed this error and seems to have loaded it, but the server still bombs out.

**Screenshots, NetDemos, & Crash Dumps**
[dehacked.zip](https://github.com/odamex/odamex/files/12479125/dehacked.zip)

**Comment by seanmleonard** [comment]
From the resource file initialization:
```Res_OpenResourceFiles: Init resource data.
adding /home/sean/odamex/resource_files/build/client/odamex.wad (352 lumps)
adding /home/sean/wads/doom2.wad (2919 lumps)
adding /home/sean/Downloads/dehacked.zip (1 lump)
```

The `dehacked.zip` file contains a single lump `DEHACKED`, which aligns the lump count printed in the console.

**Comment by seanmleonard** [comment]
The crash:
```Thread 1 "odamex" received signal SIGSEGV, Segmentation fault.
0x0000555555b3042a in ResourceCache::releaseData (this=0x0, res_id=...) at /home/sean/odamex/resource_files/common/./resources/res_cache.h:67
67			assert(res_id != ResourceId::INVALID_ID && res_id < mResourceCount);
(gdb) print res_id
$1 = {static INVALID_ID = {static INVALID_ID = <same as static member of an already seen type>, mValue = 4294967295}, mValue = 220}
```

**Comment by seanmleonard** [comment]
The crash occurs when attempting to remove the file extension of the file "DEHACKED" within the zip archive (where "DEHACKED" does not have a file extension).

Relevent code: https://github.com/odamex/odamex/blob/resource_files/common/resources/res_container.cpp#L98

**Comment by seanmleonard** [comment]
Fix has been pushed to the `resource_files` branch: https://github.com/odamex/odamex/commit/13f5fdacc5272998453b34f3da66d1452fabc0a8

**Comment by rakohus** [comment]
Solves the crash, marking resolved and filing other issues in new bugs
