### ISSUE TITLE
[CHANGE] Store player custom color so that it isn't lost when changed to a menu preset

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#897]
**What is the existing behavior? Please describe.**
Currently, changing to a color preset other than `custom` in the player options menu will wipe out the previous custom color. 

**What is the desired behavior? Why are you requesting the change?**
Store the last used custom color so that it can be reloaded when navigating back to `custom`.

**Additional context**
Players are surprised when they lose their custom color.

**Comment by Acts19quiz** [comment]
I don't get this offline in 10.4.0, unless I'm not performing the reproductions steps correctly. Could this be a goofy online interaction?

**Comment by rakohus** [comment]
I think it's just a me problem. I can't reproduce. Maybe it was all a dream
