### ISSUE TITLE
[BUG] Voodoo doll height changes visually affects player's view

### ISSUE THREAD

**Issue by thefatwilly** [odamex/odamex#917]
**Describe the bug**
When a voodoo doll travels along a conveyor and onto a sector which changes its z axis, this causes the player's view to 'jerk' exactly how it would when going up and down stairs. Bug is purely visual and does not change the player's z axis at all.

**Build that the bug occurred in**
10.4.0 stable

**To Reproduce**
Any map which has voodoo dolls on conveyors and they travel over different height sectors

**Expected behavior**
Fairly obvious

**Screenshots, NetDemos, & Crash Dumps**
Not applicable

**Additional context**
None

**Comment by rakohus** [comment]
Do you know if this occurs online as well?

**Comment by thefatwilly** [comment]
Just checked, does not happen online but it is important to note that the voodoo dolls are invisible while online so it may already be taking on different properties than in singleplayer

**Comment by rakohus** [comment]
Would you happen to have a good map, or a test map, that we can use to look at this?

**Comment by rakohus** [comment]
[odabug917test.zip](https://github.com/user-attachments/files/16487405/odabug917test.zip)

Attached is a test map I created to recreate what is described in this bug. I am not seeing this phenomenon occur, so I will mark it as won't fix for now. If you can provide more information or the wad where this occurred, I will reopen the bug and further investigate. Thanks!

**Comment by bcahue** [comment]
A good example of this is PUSS25_LUNACY.WAD MAP01 when making the first door drop by moving forward a bit. The voodoo is pushed on a floor that is lowering and the view jumps a bit during this.

**Comment by rakohus** [comment]
Got it. Made a new test wad to demonstrate: 
[odabug917test2.zip](https://github.com/user-attachments/files/16488473/odabug917test2.zip)
