### ISSUE TITLE
[FEATURE] MAPINFO allow for scrolling SKY texture

### ISSUE THREAD

**Issue by thefatwilly** [odamex/odamex#919]
**Is your feature request related to a problem? Please describe.**
When MAPINFO (possibly also ZMAPINFO) call for commands like "sky1 sky1 0.1" then this would normally lead to scrolling skies within the map as a ZDoom-based (exclusive?) feature, please could this be implemented into Odamex?

**Comment by rakohus** [comment]
I'm pretty sure this used to work. This is a feature dating back to Zdoom 1.22 or earlier.

**Comment by rakohus** [comment]
As always, a wad that you know this is used in is appreciated for testing.

**Comment by thefatwilly** [comment]
Pretty much almost all the maps in Corectf2 use this, off the top of my head core02 and core03 spring to mind.

**Comment by rakohus** [comment]
[zdm.zip](https://github.com/user-attachments/files/16042424/zdm.zip)

This old wad from 2000 has a scrolling sky on map01 for testing. Can confirm it does not work in Odamex 10.5.

**Comment by bcahue** [comment]
This was removed from Odamex in '06 because it was a Raven feature. I've created a PR to re-add this back into Odamex.

**Comment by bcahue** [comment]
Closing this as the fix is merged.
