### ISSUE TITLE
[BUG] Enemies and Items turn invisible randomly on multiplayer

### ISSUE THREAD

**Issue by Sbzro12345** [odamex/odamex#921]
**Describe the bug**
On Eviternity map32, enemies and items turn invisible on multiplayer.

**Build that the bug occurred in**
Any version after and including commit ID 373cf4bded30c856a04ad5c8400e29bffaee3d21 of stable branch

**To Reproduce**
Windows 11 Pro 64-bit OS, OS build 22621.2428. On any version of Odamex after and including commit ID 373cf4bded30c856a04ad5c8400e29bffaee3d21 of stable branch, host a multiplayer game on Eviternity map32, then join the game.

**Expected behavior**
Zombiemen alcoves turn invisible but still have physical hitbox detection and can hurt the player. Armor bonuses disappear completely and cannot be picked up.

**Screenshots, NetDemos, & Crash Dumps**
See footage. In the clip, I was killed by an invisible Pinky. https://youtu.be/QFpie_9l8mE

**Additional context**
commit ID 44f75abb13a62a34ac08672fab5b9d883a5af99e of stable branch is the last version where the bug **did not** exist.
Use command `git diff 44f75abb13a62a34ac08672fab5b9d883a5af99e..373cf4bded30c856a04ad5c8400e29bffaee3d21` to see changes from 373cf4bded30c856a04ad5c8400e29bffaee3d21 that caused the bug to occur.
Bug only works on multiplayer, on singleplayer bug does not occur

**Comment by Sbzro12345** [comment]
managed to isolate the issue to the following code block in `server/src/sv_main.cpp`:
```C
	else if (previously_ok && ok 
			&& player.mo && !mo->player && mo->type != MT_AVATAR && mo->type != MT_PLAYER 
			&& mo->on_conveyor
			&& (gametic + mo->netid) % 120) // Update items on conveyers every 120 tics
	{
		SV_SendMobjToClient(mo, cl);
		return true;
	}
```

When commenting out the entire code block above with the most recent commit ID 0880dd0976902fdf41680cf1ef33e918cf733319, enemies and items became visible again.

**Comment by Acts19quiz** [comment]
https://github.com/odamex/odamex/pull/869 For reference, this seems to be the PR in question.

**Comment by Xenaero** [comment]
Ran into this on Pina Colada map07 as well, seems to be fairly prone to the issue on 10.4. On map restart multiple players were experiencing invisible monsters across the board. Even lost soul spawning from PEs stuff will be invis until a player disconnects or connects. Either event seems to visually refresh monsters for the client. Monster projectiles unaffected.

**Comment by rakohus** [comment]
> Ran into this on Pina Colada map07 as well, seems to be fairly prone to the issue on 10.4. On map restart multiple players were experiencing invisible monsters across the board. Even lost soul spawning from PEs stuff will be invis until a player disconnects or connects. Either event seems to visually refresh monsters for the client. Monster projectiles unaffected.

Observed the same thing on this map. It's a good test case because the imps at the start will _always_ go invisible for clients after the map restart in survival mode.

**Comment by rakohus** [comment]
Should be fixed by #935. Need to test and confirm.

**Comment by cuantar** [comment]
I concur that removing the entire conditional branch mentioned above fixes the problem.  I'll test the patch in #935 this week.

**Comment by bcahue** [comment]
Patch has been out in 10.5 for a while, so I'm closing this.
