### ISSUE TITLE
[BUG] VID_FILTER doesn't appear to function

### ISSUE THREAD

**Issue by HeyItsLollie** [odamex/odamex#934]
`VID_FILTER`, originally added in v0.8.3, no longer appears to function.
`0`, `NEAREST`, `1`, `LINEAR`, `2` and `BEST` all appear to output Nearest Neighbor scaling.
v10.4.0, Windows 11 x64.

Example: `1` Linear
(`VID_320X200` is set to `1`)
![Odamex_SOLO_20240126_211135](https://github.com/odamex/odamex/assets/30498581/e65febb1-aabf-43d8-99d8-727af9891250)

**Comment by rakohus** [comment]
seems to work for me. Running at 640x480:

![image](https://github.com/odamex/odamex/assets/22926877/596b864b-fc1d-4b08-9729-5b07285d748b)

![image](https://github.com/odamex/odamex/assets/22926877/b5f1696e-46df-45d8-800e-abf31c70d2fa)
`

Can especially see it with the text:

![image](https://github.com/odamex/odamex/assets/22926877/66ced427-561e-4f36-85a7-68ea866ab9ed)

v![image](https://github.com/odamex/odamex/assets/22926877/bb9d3c30-c89e-40af-8b28-c9439aec8ab2)

![image](https://github.com/odamex/odamex/assets/22926877/69a8401d-dd87-494c-bfad-6daa536afc33)

![image](https://github.com/odamex/odamex/assets/22926877/a843bdcb-f19a-4b5f-9ddb-381ecdad519b)

**Comment by HeyItsLollie** [comment]
I figured out what was happening, chalk this one up to User Error. 😅
This is working, it just wasn't clear to me how it actually functions.

`VID_FILTER` doesn't affect `VID_320x200` or `VID_640x400` like I originally thought. These are internal rendering modes, so that you can use low resolution rendering alongside higher-resolution menus. (for example: the console and HUD messages get to enjoy way more screen space)

Additionally, my video mode was set to "Window", not "Full Screen Window".
`VID_FILTER` only comes into effect when using "Full Screen Window" alongside lower Window resolutions.

(unrelated, but fun: While using "Full Screen Window", you can also super-sample using `VID_SETMODE <WIDTH> <HEIGHT>` to force a higher resolution than what is usually available, but Odamex can crash under the wrong conditions, and you can risk making the Console impossibly small to read.)

**Comment by rakohus** [comment]
Thanks for the feedback!
