### ISSUE TITLE
[BUG] PS4 and PS5 controllers reproducibly stop working after a few minutes

### ISSUE THREAD

**Issue by cuantar** [odamex/odamex#938]
**Describe the bug**
Essentially, every (Linux) computer I have tested with either kind of controller, wired or Bluetooth, exhibits the same problem after 3-5 minutes:  The controller (and the mouse and keyboard) simply stops behaving as expected.  Odamex either is receiving lots of bogus inputs, or nothing at all.  Often Odamex must be forcibly killed in that scenario because the menu won't respond once open.

Seems fixed by PR https://github.com/odamex/odamex/pull/936.

**Build that the bug occurred in**
10.4.0

**To Reproduce**
Connect a controller to the computer, either with USB or Bluetooth.  Check `dmesg` to be sure the controller was properly set up.

I see the following:
> [Mon Feb 12 22:02:28 2024] playstation 0005:054C:09CC.0024: hidraw7: BLUETOOTH HID v1.00 Gamepad [Wireless Controller] on e8:9c:25:57:9c:a8
> [Mon Feb 12 22:02:28 2024] input: Wireless Controller as /devices/pci0000:00/0000:00:08.1/0000:2d:00.3/usb3/3-1/3-1.4/3-1.4:1.0/bluetooth/hci0/hci0:2/0005:054C:09CC.0024/input/input73
> [Mon Feb 12 22:02:28 2024] input: Wireless Controller Motion Sensors as /devices/pci0000:00/0000:00:08.1/0000:2d:00.3/usb3/3-1/3-1.4/3-1.4:1.0/bluetooth/hci0/hci0:2/0005:054C:09CC.0024/input/input74
> [Mon Feb 12 22:02:28 2024] input: Wireless Controller Touchpad as /devices/pci0000:00/0000:00:08.1/0000:2d:00.3/usb3/3-1/3-1.4/3-1.4:1.0/bluetooth/hci0/hci0:2/0005:054C:09CC.0024/input/input75
> [Mon Feb 12 22:02:28 2024] playstation 0005:054C:09CC.0024: Registered DualShock4 controller hw_version=0x0000b400 fw_version=0x0000a00a

Start Odamex and go to the `Joystick Setup` in the menu.  Set `Use Joystick` to `On`, change the `Active Joystick` to be your controller (probably something like `0: SDL 2.0 Joystick (PS...`); exit the menu and try to play through a level or two.  After about 3 minutes my controllers stopped working.

**Expected behavior**
The controller would work as it does in other games for the entire duration of play.

**Screenshots, NetDemos, & Crash Dumps**
There are none!

**Additional context**
The distribution is Funtoo Linux.  Odamex is downloaded from Github and compiled.

**Comment by ceski-1** [comment]
This was fixed by https://github.com/odamex/odamex/pull/936 and can be closed now.
