### ISSUE TITLE
[BUG] BOOM Line to Line teleport, sky flickers through walls 

### ISSUE THREAD

**Issue by Meerschweinmann** [odamex/odamex#939]
Helloho.

When i walk over a "line to line teleport" (Line-Action 244) from a BOOM map the sky flickers through the walls every time i walk over that line.

Here is a BOOM demo map:

https://www.doomworld.com/idgames/themes/TeamTNT/boom/boomedit 

When i walk the stairs up or down from the "room over room" demo or when i walk under the iced sea in the outer area, i can see this short flicker.

Used Odamex version: 10.4.0

**Comment by rakohus** [comment]
I believe this is an issue with the render interpolation. Seems to player camera to 0,0.

**Comment by Meerschweinmann** [comment]
I had the framerate uncapped, if that is helpful.

**Comment by Meerschweinmann** [comment]
Update: with framerate capped at 35fps the short flicker is gone. 
But even 35fps were a not really reachable dream on my 486 back in the days, it is really juddery today :)

**Comment by rakohus** [comment]
Include as duplicate of #564.
