### ISSUE TITLE
[BUG] MAPINFO skill property "name" looks for a lump entered after "name" rather than present a string.

### ISSUE THREAD

**Issue by Acts19quiz** [odamex/odamex#947]
**Describe the bug**
In [MAPINFO (old format)](https://zdoom.org/wiki/MAPINFO_(old_format)), specifically when defining new skills, the `picname` property is supposed to be the name of the skill as a lump (e.g., `PicName "M_JKILL"`). The `name` property is just raw text (e.g., `name "My New Skill"`). However, when using 'name' property, Odamex will erroneously look for a lump with the text entered after `name`.  Selecting NEW GAME in the menu forcefully exits the game to the console with the following error message:

> ERROR: W_GetNumForName: &lt;string&gt; not found!
(checked in: ODAMEX.WAD, &lt;iwad&gt;, &lt;pwad&gt;)

**Build that the bug occurred in**
10.4.0 G46E0E1-8728

**To Reproduce**
Make a MAPINFO with a new or redefined skill, using the `name` property instead of `picname`.

**Expected behavior**
For Odamex to display text strings in the menu matching what's given in MAPINFO for skill names in place of `picname` lumps.

**Screenshots, NetDemos, & Crash Dumps**
This is what the below test WAD looks like in ZDoom:
![MAPINFO_skill](https://github.com/odamex/odamex/assets/63941237/7784a36b-d072-4bb7-a92c-2801d92aa3ed)

**Additional context**
A demo WAD:
[mapinfo_skill.zip](https://github.com/odamex/odamex/files/14817062/mapinfo_skill.zip)

**Comment by bcahue** [comment]
Odamex currently doesn't support text as an entry for `episode` in UMAPINFO, or `name` for `skill`. It's stubbed out for episode:

```c++
void SetupEpisodeList()
{
	for (int i = 0; i < episodenum; ++i)
	{
		if (EpisodeInfos[i].fulltext)
		{
			// Not implemented
	 	}
	 	else
	 	{
			strncpy(EpisodeMenu[i].name, EpisodeInfos[i].name.c_str(), 8);
	 	}
  
	 	EpisodeMenu[i].alphaKey = EpisodeInfos[i].key;
  	}
}
```

but puts the `name` untranslated into the variable meant for a `picname`:

```c++
void SetupSkillList()
{
	NewDef.lastOn = defaultskillmenu;

	int i = 0;
	for (; i < skillnum; ++i)
	{
		if (SkillInfos[i].pic_name.empty())
		{
			strncpy(NewGameMenu[i].name, SkillInfos[i].menu_name.c_str(), 8);
		}
		else
		{
			strncpy(NewGameMenu[i].name, SkillInfos[i].pic_name.c_str(), 8);
		}

		NewGameMenu[i].alphaKey = SkillInfos[i].shortcut;
	}

	strncpy(NewGameMenu[i].name, "\0", 1);
	NewGameMenu[i].alphaKey = 'p';
}
```

Short term fix would be to disable and warn, long term would be to implement picname as well as name for `episode` (UMAPINFO) and `skill` (MAPINFO)

**Comment by bcahue** [comment]
Fixed in current `stable`:

![image](https://github.com/user-attachments/assets/3f3244c0-e7a8-42d4-b842-0b3bee4327e6)
